### ISSUE TITLE
[BUG]SYSTEM_INIT_MESSAGE_ROLE不是system时出错

### ISSUE THREAD

**Issue by sandlong** [TBXark/ChatGPT-Telegram-Workers#101]
**版本号**
[1.3.0 release]
- ts: `1678546663`
- sha: `94c81f1`

**描述问题**
当SYSTEM_INIT_MESSAGE_ROLE值不是system，比如设定为user时，与chatbot交谈第二句话就会返回OpenAI API 错误。
值是system时是正常的。
是不是这功能还没做好😥

**截图**
![image](https://user-images.githubusercontent.com/47054753/224503554-dbd89564-a040-4769-a4b1-8c2a17a0deeb.png)

**Comment by sandlong** [comment]
另外好像自动截断历史对话的功能也没有效果，不知是我个人的问题还是依然没有完成😥

**Comment by TBXark** [comment]
SYSTEM_INIT_MESSAGE_ROLE 这个修复了，历史记录这个我再看看

**Comment by TBXark** [comment]
历史记录应该是没有问题，你是看KV里面还有缓存吗？

**Comment by sandlong** [comment]
> 历史记录应该是没有问题，你是看KV里面还有缓存吗？

是的，/new之后的全部对话都存着。
但最主要的原因是我总是遇到API说超过4096，就好像这个功能完全不生效一样。按理说超过20回合就截断的话不可能有这种情况。

比如我让MAX_HISTORY_LENGTH=5，再和chatbot测试对话
![image](https://user-images.githubusercontent.com/47054753/224541726-7021cc63-fcfd-4b87-b497-2c27255be347.png)
![image](https://user-images.githubusercontent.com/47054753/224541862-c311f748-0ef9-45e7-9f99-caec1eec30e3.png)
如果历史记录会自动截断的话不应该有这种情况。

但看起来应该是我自己的问题？😢我去重新部署一下算了

**Comment by TBXark** [comment]
AUTO_TRIM_HISTORY 设置成 true 了吗

**Comment by sandlong** [comment]
是的。但是我之后把Environment Variables里的AUTO_TRIM_HISTORY删了，因为我看默认就是TRUE。
再试验了一次，貌似这次管用了
![image](https://user-images.githubusercontent.com/47054753/224544303-a07092a6-e9a2-402d-a35d-37de7636252d.png)

**Comment by mithew** [comment]
> > 历史记录应该是没有问题，你是看KV里面还有缓存吗？
> 
> 是的，/new之后的全部对话都存着。 但最主要的原因是我总是遇到API说超过4096，就好像这个功能完全不生效一样。按理说超过20回合就截断的话不可能有这种情况。
> 
> 比如我让MAX_HISTORY_LENGTH=5，再和chatbot测试对话 ![image](https://user-images.githubusercontent.com/47054753/224541726-7021cc63-fcfd-4b87-b497-2c27255be347.png) ![image](https://user-images.githubusercontent.com/47054753/224541862-c311f748-0ef9-45e7-9f99-caec1eec30e3.png) 如果历史记录会自动截断的话不应该有这种情况。
> 
> 但看起来应该是我自己的问题？😢我去重新部署一下算了

你的指令太简单了，删除大部分聊天记录 ChatGPT 也能接的上(也就是说，ChatGPT 接的上不代表记录删除失败)

**Comment by sandlong** [comment]
> > > 历史记录应该是没有问题，你是看KV里面还有缓存吗？
> > 
> > 
> > 是的，/new之后的全部对话都存着。 但最主要的原因是我总是遇到API说超过4096，就好像这个功能完全不生效一样。按理说超过20回合就截断的话不可能有这种情况。
> > 比如我让MAX_HISTORY_LENGTH=5，再和chatbot测试对话 ![image](https://user-images.githubusercontent.com/47054753/224541726-7021cc63-fcfd-4b87-b497-2c27255be347.png) ![image](https://user-images.githubusercontent.com/47054753/224541862-c311f748-0ef9-45e7-9f99-caec1eec30e3.png) 如果历史记录会自动截断的话不应该有这种情况。
> > 但看起来应该是我自己的问题？😢我去重新部署一下算了
> 
> 你的指令太简单了，删除大部分聊天记录 ChatGPT 也能接的上(也就是说，ChatGPT 接的上不代表记录删除失败)

接的上是正常的，但关键是我最后问它这个数字是什么意思，如果没有历史对话记录的支持它是回答不了的，比如我下面那次实验，它完全不知道我在问什么
