### ISSUE TITLE
[BUG] 发送编辑消息之后程序报错

### ISSUE THREAD

**Issue by philipli1995** [TBXark/ChatGPT-Telegram-Workers#103]
**描述问题**
不小心点了编辑之前发送的消息然后发送，之后就bot就一直发送/new无回应，发送其他文字就会报错。
请问应该如何解决？😥

**错误日志**
 "exceptions": [
    {
      "name": "TypeError",
      "message": "Cannot read properties of undefined (reading 'chat')",
      "timestamp": 1678629712187
    }
  ],
  "logs": [],
  "eventTimestamp": 1678629712187,
  "event": {
    "request": {
      "url": "https://soft-fog-4df1.xxxxxxxx.workers.dev/telegram/XXXXXXXXX:REDACTED/webhook",
      "method": "POST"
    }
]

**Comment by TBXark** [comment]
更新 [dev](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/dev/dist/index.js) 这本版本试一下

**Comment by philipli1995** [comment]
> 更新 [dev](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/dev/dist/index.js) 这本版本试一下

自己建了一个新的bot，重新按流程部署一下就好了。不管怎样，非常感谢回复~
