### ISSUE TITLE
【询问】MAX_HISTORY_LENGTH 数值范围

### ISSUE THREAD

**Issue by vicevolf** [TBXark/ChatGPT-Telegram-Workers#106]
个人不是很理解 MAX_HISTORY_LENGTH 的数值范围，看到表格右侧最大的是4096，但缺省值是20…… 请问这个数值的范围一般是多少？

**Comment by Cheivin** [comment]
实际上`MAX_HISTORY_LENGTH`指的是对话记录数，而你说的`4096`是`AUTO_TRIM_HISTORY`变量的特殊说明。目前为了达到持续对话，需要把聊天历史一并发送，由于ChatGPT的对话有4096个token的限制，过长的内容可能造成CHatGPT的接口报错。因此打开`AUTO_TRIM_HISTORY`配置可以让机器人自动裁剪对话记录，尽量避免超过4096。

https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/fa3cd3dfabfd0968b16682831d1dae30775630b0/src/message.js#L332-L353

**Comment by vicevolf** [comment]
懂了，这个 MAX_HISTORY_LENGTH 值是对话次数是吧

**Comment by Cheivin** [comment]
准确说是聊天记录数。就比如这个issue，算上我这一条，一共4条聊天记录。
