### ISSUE TITLE
[BUG]ERROR:CHAT: OpenAI API 错误 > Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by shmily0818** [TBXark/ChatGPT-Telegram-Workers#107]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`

**描述问题**
简要而清晰地解释问题。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
你是不是设置`OPENAI_API_DOMAIN`这个变量了
