### ISSUE TITLE
[BUG]私聊机器人偶尔变回复某条消息

### ISSUE THREAD

**Issue by vicevolf** [TBXark/ChatGPT-Telegram-Workers#109]
**版本号**
当前已经是最新版本, 当前版本: {"ts":1678363377,"sha":"7b9b91f"}

**描述问题**
一个奇怪的bug，与机器人私聊时，偶尔机器人的发言会变成“回复”某条消息，而且回复的聊天气泡都很远。

**复现问题**
与机器人私聊一段时间，有概率会出现bug，之后机器人本该直接发送的消息，都会回复之前的某条消息。

我尝试new等命令，机器人一样还是回复。

我尝试从tg清空了和机器人都在私聊记录，发现机器人甚至不会应答了。

我又访问了Cloudflare的初始化网址，之后机器人的消息就恢复正常了。

但后来还是会偶尔遇到这个问题。

**预期行为**
简要而清晰地说明预期的行为。

**截图**
![IMG_20230316_011038.jpg](https://user-images.githubusercontent.com/47265026/225387471-9bae1d6d-fd29-4e91-9c6e-2865f06c1b32.jpg)

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
有可能是这个回调报错了，tg收到非200的响应就会重试。dev分支做了一点处理，你可以试一下。
