### ISSUE TITLE
[BUG] 提示ERROR:CHAT: OpenAI API 错误

### ISSUE THREAD

**Issue by nagaame** [TBXark/ChatGPT-Telegram-Workers#111]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `1678546663`
- sha: `94c81f1`

**描述问题**
使用自定义的`SYSTEM_INIT_MESSAGE`, 第一次对话没有问题， 第二次对话提示这个错误，猜测官方api不再使用该参数。
```
ERROR:CHAT: OpenAI API 错误
> Additional properties are not allowed ('cosplay' was unexpected) - 'messages.1'

```

**复现问题**

init之后，使用`/new` 和`/start` 初始化机器人，第一轮对话没有问题，第二轮对话提示出错

KV存储内容如下

`history`:

`[{"role":"system","content":"现在开始你是喵娘，每句话以喵结尾"},{"role":"user","content":"你是谁","cosplay":""},{"role":"assistant","content":"我是AI助手，喵~","cosplay":""}]`

`user_config`:

`{"SYSTEM_INIT_MESSAGE":"现在开始你是喵娘，每句话以喵结尾","OPENAI_API_EXTRA_PARAMS":{}}`

**预期行为**
可以一直对话下去

**截图**

![](https://user-images.githubusercontent.com/6214936/225548875-6630b952-35db-448b-a7c0-1f8c6831c6fe.png)

**其他信息**

env设置：

```

API_KEY	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
BOT_NAME	KChatGPTBot
CHAT_GROUP_WHITE_LIST	12345678,12345678,12345678
CHAT_WHITE_LIST	12345678,12345678,12345678
ENABLE_USAGE_STATISTICS	true
GROUP_CHAT_BOT_ENABLE	true
GROUP_CHAT_BOT_SHARE_MODE	false
I_AM_A_GENEROUS_PERSON	false
SYSTEM_INIT_MESSAGE	现在开始你是喵娘，每句话以喵结尾
SYSTEM_INIT_MESSAGE_ROLE	user
TELEGRAM_AVAILABLE_TOKENS	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TELEGRAM_BOT_NAME	KChatGPTBot
WORKERS_DOMAIN	example.com

```

**Comment by TBXark** [comment]
更新master分支dist文件夹下最新版代码可以解决
