### ISSUE TITLE
【建议】释放聊天历史时，保护 Prompts

### ISSUE THREAD

**Issue by vicevolf** [TBXark/ChatGPT-Telegram-Workers#112]
注意到当与机器人聊天超过 MAX_HISTORY_LENGTH 所设置的20次对话时，机器人的聊天风格出现了明显变化，这有些影响聊天体验。

个人理解，设定好 Prompts 后，Prompts 是作为第一句对话发给AI的。当触发 MAX_HISTORY_LENGTH 时，第一句对话就被释放掉了，之后释放第二三句对话？导致ai产生了明显变化。

能否在释放聊天历史时，保护 Prompts ?直接去释放二三句对话。

![Screenshot_2023-03-16-15-55-18-198_org.telegram.messenger-edit.jpg](https://user-images.githubusercontent.com/47265026/225551205-0f5982c7-75bd-4347-a6f6-1cab9d19f09c.jpg)

如上图，在20次对话前AI在扮作家演角色与用户对话，20次后就明显是AI在分析了。

**Comment by vicevolf** [comment]
抱歉，我设置了自动回复，导致机器人自动开始新对话了，没有抓到kv的记录验证我的猜想。

**Comment by TBXark** [comment]
可能你每次对话比较长导致裁剪的历史记录比较多，你可以试一下新的master分支的代码，稍微优化了token长度的计算
