### ISSUE TITLE
[BUG]机器人回复速度很慢，而且有概率不回复

### ISSUE THREAD

**Issue by RIFTaReLINK** [TBXark/ChatGPT-Telegram-Workers#115]
之前一直都是秒回复，在某个时间点（似乎是GPT4发布之后）回复速度就变得特别慢，经常在机器人的“输入中”状态结束之后很久才有回复，而且很容易触发API错误提示（提示负载过高，所以推测是Openai那边的问题）
但机器人还容易出现有“输入中”但没有回复的情况。我试过另一个被部署于cloud flare上的网页界面api项目，回复速度同样变得很慢，但回复速度比机器人快一点且没有发现不回复的问题。
是否有可能是因为cloudflare worker与机器人之间的某些机制导致了吞回复的现象？

**Comment by TBXark** [comment]
输入中不是真的输入中而是前面一系列中间件都走完了开始调用openai的api了，可能最后openai报错或者超时了。

**Comment by yiiyahui** [comment]
很明显这是openai的问题。目测18刀用完付费就没这个问题了
