### ISSUE TITLE
关于群组中的 `SYSTEM_INIT_MESSAGE`

### ISSUE THREAD

**Issue by inertia42** [TBXark/ChatGPT-Telegram-Workers#12]
现在在群组中使用 bot，`SYSTEM_INIT_MESSAGE`好像还是根据发送`/new`命令的人而定的，请问能否在 `GROUP_CHAT_BOT_SHARE_MODE` 选项开启时，将 `SYSTEM_INIT_MESSAGE` 的设置改为视群组而定。

**Comment by TBXark** [comment]
是的，现在`SYSTEM_INIT_MESSAGE ` 是属于用户自己独立的配置。如果每个群都要自己的配置，这里可能涉及到一个权限的问题了，很容易变成每个人都能修改这个配置，毕竟没有办法知道群主是谁。
可以修改代码,不加载用户信息，然后自己手动配置`USER_CONFIG`, 然后专门给这个群建一个机器人和workers
```js
async function initUserConfig(id) {
```

**Comment by TBXark** [comment]
找到解决办法 已经在dev分支中优化，完成后合并到主分支

**Comment by TBXark** [comment]
可以试一下当前master分支[新版](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js) 然后将环境变量的`GROUP_CHAT_BOT_SHARE_MODE`设置成false

如果出问题想回滚可以使用这个版本 [旧版](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/0f70b37d482a8262c23aea4b62fa85feff8161eb/index.js)

**Comment by TBXark** [comment]
> > 可以试一下当前master分支[新版](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js) 然后将环境变量的`GROUP_CHAT_BOT_SHARE_MODE`设置成`true`
> > 如果出问题想回滚可以使用这个版本 [旧版](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/0f70b37d482a8262c23aea4b62fa85feff8161eb/index.js)
> 
> 请问现在只能通过回复 bot 的信息来使用，而不能通过 at 了吗？
> 
> 另外 readme 关于 SETENV 的部分应该要更新一下，我看代码里好像都改成了命令格式。

readme更新了，`master`和`dev`我都试了一下 可以用 at 回答问题。要不要你更新一下代码。

**Comment by TBXark** [comment]
@inertia42 
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/9513891/223107978-0ad1d8cf-83db-4e8d-a201-d1666b087fdd.png">

**Comment by TBXark** [comment]
> @TBXark 看了一会源码终于搞清楚了，现在在群聊中使用 `/new` 命令必须要 at bot，如果群聊中不加 at 就会导致 bot （包括私聊）卡住。

是 不过你可以直接 / 然后就会弹出来让你选机器人的命令了
