### ISSUE TITLE
[性能问题] 脚本经常超过cpu限制导致回复卡顿

### ISSUE THREAD

**Issue by Respawn-ID** [TBXark/ChatGPT-Telegram-Workers#124]
经常脚本超过worker本身限制的性能造成机器人卡顿
![Screenshot_20230321_154248_com android chrome](https://user-images.githubusercontent.com/30469542/226544294-ac906ed6-1390-4e99-ad08-785ec62168ed.jpg)

**Comment by TBXark** [comment]
dev加了个安全模式, 设置环境变量  `SAFE_MODE=true`，能解决超时导致的循环回调的问题
