### ISSUE TITLE
[建议] 可以通过编辑之前的消息，重新生成回答吗

### ISSUE THREAD

**Issue by uJZk** [TBXark/ChatGPT-Telegram-Workers#125]
或者也可以变成通过回复之前的消息，重新新生成回答
大概类似于官方网页版修改历史消息的效果

**Comment by TBXark** [comment]
理论上是可以的，得稍微重构一下代码，必须记住两个问答对话消息的ID。判断被修改的ID在历史记录中，当一个对话被修改的时候，同步的去修改那个回答的消息。

**Comment by TBXark** [comment]
不过这个太麻烦了，按理说一般不会修改很久之前的对话数据，我觉得可以加个命令。
`/regenerate` 直接输入默认重新生成一个回答，比如对上一个不满意重新生成。
`/regenerate  被修改过的问题`, 使用被修改过的问题重新生成回答

**Comment by TBXark** [comment]
最新`dev` 分支可以用`/redo`指令重新获取一个新的回答,或者`/redo 修改过的提问`重新生成回答
