### ISSUE TITLE
[咨询] 模型不是chatgpt3 ？

### ISSUE THREAD

**Issue by exposir** [TBXark/ChatGPT-Telegram-Workers#126]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/33340988/226836672-78c73f1c-e711-423e-9b7e-7481c5da0804.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/33340988/226836900-2311e809-9c36-474c-96ad-d8fa2df0688a.png">

**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`

**描述问题**
简要而清晰地解释问题。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
没有 `chatgpt3`  就是叫`gpt-3.5-turbo`, 你去网页版估计也这么回答
