### ISSUE TITLE
【建议】能否添加一个更换openai的key的功能

### ISSUE THREAD

**Issue by jyogyou** [TBXark/ChatGPT-Telegram-Workers#127]
每个月18刀，用完后能不能用另外一个apikey来自动替换。如果能出这个功能就方便了

**Comment by TBXark** [comment]
现在手动修改环境变量就行了。一个账号应该不止用一个月。

**Comment by TBXark** [comment]
dev 分支 加了一个`/setenv OPENAI_API_KEY=sk-xxxx` 可以自行给自己换openai key 的功能。
