### ISSUE TITLE
[咨询] 模型不是chatgpt3？并且在网页版里做了对比

### ISSUE THREAD

**Issue by exposir** [TBXark/ChatGPT-Telegram-Workers#128]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/33340988/226860318-43f7b0af-a6c6-4383-ab9d-486d814f54af.png">

<img width="891" alt="image" src="https://user-images.githubusercontent.com/33340988/226860447-71f934f9-f678-494d-8769-e946b727f093.png">

经过测试 模型准确度类似于chatgpt2

**Comment by TBXark** [comment]
API 和 网页版 是有差距的。不是模型的区别。没有chatgpt2这种模型

<img width="811" alt="image" src="https://user-images.githubusercontent.com/9513891/226861989-719bd33b-f850-4f1a-a173-1c0c336a75b4.png">

**Comment by TBXark** [comment]
https://platform.openai.com/docs/models/model-endpoint-compatibility
<img width="681" alt="image" src="https://user-images.githubusercontent.com/9513891/226862268-ef67b4ff-c668-4bc8-9d95-f9dc9026ea54.png">
