### ISSUE TITLE
[BUG]Webhook: {"ok":false,"error_code":429,"description":"Too Many Requests: retry after 1","parameters":{"retry_after":1}}

### ISSUE THREAD

**Issue by zjwangmin** [TBXark/ChatGPT-Telegram-Workers#131]
经常出现查询没有反应，然后重新初始化就会提示：
Webhook: {"ok":false,"error_code":429,"description":"Too Many Requests: retry after 1","parameters":{"retry_after":1}}

**Comment by TBXark** [comment]
版本号是什么？

**Comment by TBXark** [comment]
你是回复引用了图片吗

**Comment by zjwangmin** [comment]
回复没有引用img标签

**Comment by TBXark** [comment]
我意思是引用机器人返回的那个图

**Comment by zjwangmin** [comment]
怎么引用机器人回复的图片

**Comment by TBXark** [comment]
没事 那就是没有了。其实图片和聊天是独立的两个功能。按理说应该没有什么影响。回头我debug一下。

**Comment by TBXark** [comment]
应该是某个地方tg回调失败，然后循环回调了。

**Comment by zjwangmin** [comment]
谢谢

**Comment by TBXark** [comment]
> 昨天的代码 还有一个问题就是img生成照片后 如果对照片有意见再回复是没有反应的 像假死

是dev分支的代码吗。dev分支有点BUG刚才修复了一下.

**Comment by zjwangmin** [comment]
master分支的

**Comment by TBXark** [comment]
em，要不你试一下dev分支。

**Comment by zjwangmin** [comment]
OK 谢谢

**Comment by zjwangmin** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1037786/227413427-00c841b9-4744-4d66-921d-ab6c0e934365.png">
dev分支的 也会出现类似的问题。

**Comment by zjwangmin** [comment]
然后重新初始化之后又可以/new开始新的会话

**Comment by TBXark** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/9513891/227414390-07c651c4-0326-422a-86a1-598dfb46be04.png">
挺玄学啊

**Comment by TBXark** [comment]
dev加了个安全模式, 设置环境变量  `SAFE_MODE=true`，能解决循环回调的问题

**Comment by zjwangmin** [comment]
五点左右用dev分支最新代码 干脆啥反应都没了 后来又换回去master分支

**Comment by TBXark** [comment]
有bug， 已经删掉了这部分代码。cf禁止了递归调用。但是本地调试却没有这个限制。
________________________________

**Comment by Cpunek0** [comment]
Vggb
