### ISSUE TITLE
[BUG]权限不足,需要administrator,creator,当前:member

### ISSUE THREAD

**Issue by 91pic** [TBXark/ChatGPT-Telegram-Workers#133]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
当前已经是最新版本, 当前版本: {"ts":1678945730,"sha":"9e23846"}

**描述问题**
群聊只有管理员能使用机器人，其他群成员都提示权限不足。
CF变量设置：
I_AM_A_GENEROUS_PERSON | true

**Comment by TBXark** [comment]
I_AM_A_GENEROUS_PERSON 其实不用开。 加群ID到白名单了吗。有一些命令只有管理员才能用

**Comment by TBXark** [comment]
刚才试了一下，应该就是没有把机器人加到白名单里面了
- 必须把群ID加到白名单CHAT_GROUP_WHITE_LIST才能使用, 否则任何人都可以把你的机器人加到群组中，然后消耗你的配额。
- 受限TG的隐私安全策略，如果你的群组是公开群组或超过2000人，请将机器人设置为管理员，否则机器人无法响应@机器人的聊天消息。
