### ISSUE TITLE
将机器人添加到群组，发送消息机器人没有反应[BUG]

### ISSUE THREAD

**Issue by yangmingyuan380** [TBXark/ChatGPT-Telegram-Workers#135]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `1678945730`
- sha: `9e23846`

**描述问题**
我按照配置文件，将GROUP_CHAT_BOT_ENABLE、TELEGRAM_BOT_NAME、CHAT_GROUP_WHITE_LIST都进行了设置，结果将机器人添加到群聊后，发送任何消息机器人都没有反应。

**复现问题**
重现问题的步骤：
1. 将机器人添加到群组
2. 发送任意消息

**预期行为**
希望机器人在群组中可以正常使用

**截图**

![image](https://user-images.githubusercontent.com/32832374/227702808-b22a9c67-8190-45b0-86d3-a89d9f9ff991.png)

![image](https://user-images.githubusercontent.com/32832374/227702749-1204265c-9e01-45c5-b78d-a9fdbcd05c79.png)

**Comment by TBXark** [comment]
https://github.com/TBXark/ChatGPT-Telegram-Workers/discussions/122

1. 受限TG的隐私安全策略，如果你的群组是公开群组或超过2000人，请将机器人设置为管理员，否则机器人无法响应@机器人的聊天消息。
2. 必须在botfather中设置/setprivacy为Disable，否则机器人无法响应@机器人的聊天消息。
