### ISSUE TITLE
报这个错误，是因为什么原因？appkey的问题吗？

### ISSUE THREAD

**Issue by jamesleeon** [TBXark/ChatGPT-Telegram-Workers#136]
ERROR:CHAT: OpenAI API 错误
> Invalid URL (POST /v1/chat/completions)
参数: {"model":"gpt-3.5-turbo","messages":{"role":"system","content":"你是一个得力的助手"},{"role":"user","content":"你是谁？"}}

**Comment by TBXark** [comment]
你是不是设置 OPENAI_API_DOMAIN 了

**Comment by jamesleeon** [comment]
没有设定，仅仅设定了3个变量。API_KEY ， CHAT_WHITE_LIST ，TELEGRAM_AVAILABLE_TOKENS

**Comment by TBXark** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9513891/228873313-dea8bc13-c149-4fd6-a03b-286b7971ef54.png">
其他人用其他框架和语言好像也遇到类似的问题，应该是那个ip被openai限制了

**Comment by jamesleeon** [comment]
好的，感谢，我怀疑也是ip问题导致。不知道这个ip的策略是什么...

**Comment by heypig** [comment]
我用了opencat之后,  提示You exceeded your current quota, please check your plan and billing details.

之后用telegram bot也遇到这个提示.      即使我申请了两个不同api_key (bot和opencat各自一个)

**Comment by TBXark** [comment]
> 我用了opencat之后, 提示You exceeded your current quota, please check your plan and billing details.
> 
> 之后用telegram bot也遇到这个提示. 即使我申请了两个不同api_key (bot和opencat各自一个)

最近在大规模封账号，可以登陆官网看看自己账号情况
