### ISSUE TITLE
[consultation]

### ISSUE THREAD

**Issue by WooyJen** [TBXark/ChatGPT-Telegram-Workers#138]
您好，我是想问一下这个bot用cf部署后，在tg里对话时需要在clash里给tg设置分流走美国，还是直接设置domain-suffix openai.com走美国，而tg可以随便走哪比如ChatGPT不支持的香港节点。

**Comment by TBXark** [comment]
不用做处理，我都是没做处理的能正常使用。api应该是没有地区限制。只是web端有。
