### ISSUE TITLE
[问题]请问下，我部署上去，而且成功了。但是在tg的机器人里输入/new 提示Unrecognized command. Say what?是什么原因呢？感谢！

### ISSUE THREAD

**Issue by jackZhang8532290** [TBXark/ChatGPT-Telegram-Workers#139]
请问下，我部署上去，而且成功了。但是在tg的机器人里输入/new 提示Unrecognized command. Say what?是什么原因呢？感谢！

**Comment by TBXark** [comment]
截个图看看？运行init接口了吗

**Comment by jackZhang8532290** [comment]
&nbsp;


694897585
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 中午11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TBXark/ChatGPT-Telegram-Workers] [问题]请问下，我部署上去，而且成功了。但是在tg的机器人里输入/new 提示Unrecognized command. Say what?是什么原因呢？感谢！ (Issue #139)





 
截个图看看？运行init接口了吗

**Comment by TBXark** [comment]
截图看不到
