### ISSUE TITLE
[BUG] 部署 GPT-4 版本后端后，API会一直在固定时间间隔后被反复请求

### ISSUE THREAD

**Issue by mengwangme** [TBXark/ChatGPT-Telegram-Workers#140]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `1678945730 `
- sha: `9e23846`

**描述问题**

配置变量 CHAT_MODEL 为 gpt-4后，API就一直在被恶意反复请求，请求间隔固定且为5分钟。请问出现这种原因的现象是什么呢？
CHAT_WHITE_LIST 也已经设置，应该不存在他人调用 bot 的可能。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
<img width="241" alt="Screenshot 2023-03-28 at 13 42 02" src="https://user-images.githubusercontent.com/17667396/228130212-8bf74b90-98fa-483a-97c3-9716219c0f0c.png">

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
有可能某个提问导致workers cpu 超时，导致回调失败了 TG一直在重试

**Comment by TBXark** [comment]
你要不要试一下先把白名单清空，群白名单也清空。 然后让他回调成功一次。过五分钟再恢复。

**Comment by mengwangme** [comment]
> 有可能某个提问导致workers cpu 超时，导致回调失败了 TG一直在重试

可能是这个原因，后面一直发 Prompt，Bot 也没有任何反应了。出现超时这种问题可以提醒一下吗？

> 你要不要试一下先把白名单清空，群白名单也清空。 然后让他回调成功一次。过五分钟再恢复。

为什么把白名单清空就能成功回调呢？
我已经把这个 Service 给删除了，之后遇到同样问题的人可以试一下。

**Comment by TBXark** [comment]
@mengwangme  就是workers处理超时然后报错给telegram，然后重试然后还是超时，无限循环。workers没有给一个超时处理的方法，目前是无解。

**Comment by TBXark** [comment]
@mengwangme  清空白名单的操作后，workers处理起来就会非常快，里面给刚才报错的消息返回一个成功处理的结果（没有权限）。然后tg就不会重试这条消息了。

**Comment by TBXark** [comment]
遇到超时假死可以尝试设置环境变量 `GPT3_TOKENS_COUNT ` 为 `false` 加快处理速度。

**Comment by mengwangme** [comment]
@TBXark 
谢谢回答，我现在关闭这个问题。

**Comment by binux** [comment]
我也遇到了这个问题，严重的时候一天被刷了$8。
看了一下代码，或许可以在history 中记录一下 "message_id"，检查最后一个 history 的 message_id 是否一致，如果遇到重放的，，直接返回错误？

**Comment by TBXark** [comment]
最新版master分支1.5.0添加了这个功能 你可以更新一下
________________________________
