### ISSUE TITLE
Webhook: {"ok":true,"result":true,"description":"Webhook was set"}  Command: {"ok":true,"result":{"all_private_chats":{"ok":true,"result":true},"all_group_chats":{"ok":true,"result":true},"all_chat_administrators":{"ok":true,"result":true}}}提示看部署成功，TG上怎么找到机器人开始对话？[BUG]

### ISSUE THREAD

**Issue by realall** [TBXark/ChatGPT-Telegram-Workers#141]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`

**描述问题**
简要而清晰地解释问题。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
重botfather 用/mybots里面找到自己的机器人，点击名字开始聊天
