### ISSUE TITLE
[Question] 怎么让 `/role <character> key=value` 的方式设置的角色生效

### ISSUE THREAD

**Issue by Kosette** [TBXark/ChatGPT-Telegram-Workers#142]
设置了之后，`/role show`查看也成功保存了，但是没找人任何可以调用角色设定的地方，现在好像还是只能`/setenv key=value`的方式设置角色提示。有方法能快速调用设定好的角色吗？

**Comment by TBXark** [comment]
`~角色名 问题`
`~翻译 把这句话翻译成英文：你好世界`
