### ISSUE TITLE
【建议】api 余额查询功能

### ISSUE THREAD

**Issue by DoingDog** [TBXark/ChatGPT-Telegram-Workers#143]
是否能增加一个指令查询api余额的功能，直接看到api key的使用量

这是网上搜到的一个办法。但不知道能否在机器人上使用
https://community.openai.com/t/get-the-remaining-credits-via-the-api/18827

https://www.powershellgallery.com/packages/PS-OpenAI/0.3.0-beta/Content/Src%5CPublic%5CGet-OpenAICreditGrants.ps1

**Comment by TBXark** [comment]
账单好像的只能用session key获取, 得稍微改点东西。之后有空可以加一下。
```json
{
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

```

**Comment by TBXark** [comment]
dev分支已添加
