### ISSUE TITLE
机器人添加到群不工作

### ISSUE THREAD

**Issue by xiaoyuer0408** [TBXark/ChatGPT-Telegram-Workers#147]
添加到群 有选项按钮但是不回复信息

**Comment by TBXark** [comment]
- 配置`GROUP_CHAT_BOT_ENABLE `为`true`
- 配置`TELEGRAM_BOT_NAME`, 机器人名字 `xxx_bot`, 顺序必须和TELEGRAM_AVAILABLE_TOKENS 一致, 必须设置否则无法在群聊中使用
- 必须把群ID加到白名单`CHAT_GROUP_WHITE_LIST`才能使用, 否则任何人都可以把你的机器人加到群组中，然后消耗你的配额。
- 受限TG的隐私安全策略，如果你的群组是公开群组或超过2000人，请将机器人设置为管理员，否则机器人无法响应@机器人的聊天消息。
- 必须在`botfather`中设置`/setprivacy`为`Disable`，否则机器人无法响应@机器人的聊天消息。

**Comment by HaveF** [comment]
好用，没问题。刚试验成功了。只不过好像调整完 chat group white list 之后，[需要再初始化一下](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/doc/DEPLOY.md#%E5%85%AD-%E5%88%9D%E5%A7%8B%E5%8C%96)
