### ISSUE TITLE
[doc]文档问题

### ISSUE THREAD

**Issue by HaveF** [TBXark/ChatGPT-Telegram-Workers#148]
请问[文档中](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/doc/CONFIG.md)

`/role 设置预设的身份`

是什么意思呢？我看 [openAI 里面有三种 role](https://platform.openai.com/docs/guides/chat/introduction)
默认流程是设置完 `system` 之后，交互都是 `user`, 是吗？

**Comment by TBXark** [comment]
这个是可以在聊天的时候临时调用另外一个身份的功能。 
比如临时要翻译就 `~翻译 把这句话翻译成中文:hello world`

**Comment by HaveF** [comment]
哦，你看我理解的对不对：

另外的身份就相当于打开了一个聊天小窗，只发送这一句的内容给这个身份
这是个动态链接库啊 💡💡💡

这个真的很碉堡啊，文档中没看到这个用法

**Comment by TBXark** [comment]
差不多这个意思， 每个角色有自己的历史记录 ，不和其他的冲突。 但是得每次调用前得加前缀。用法有点复杂，就没写文档了。
________________________________
