### ISSUE TITLE
[BUG]n 参数有问题

### ISSUE THREAD

**Issue by HaveF** [TBXark/ChatGPT-Telegram-Workers#149]
**版本号**
- ts: `1680598939 `
- sha: `dcf6af4`
- branch: master
{"sha": "dcf6af4", "timestamp":}
其实就是昨晚的版本

**描述问题**
[n的参数](https://platform.openai.com/docs/api-reference/chat/create#chat/create-n)设置之后不起作用
`/setenv OPENAI_API_EXTRA_PARAMS={"n":3}`

只回复一个答案

**Comment by TBXark** [comment]
额 应该就是回复了三个，但是我的代码不支持返回三个。我就取了第一个返回
