### ISSUE TITLE
`historyKey` 构造错误

### ISSUE THREAD

**Issue by inertia42** [TBXark/ChatGPT-Telegram-Workers#15]
https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/28fb147fcdc6208f0b3805f0f2b0ba72bdf97b4f/index.js#L215
处理 `historyKey` 时，这里已经加上了 bot id，但是在 `msgCreateNewChatContext` 中又重复了一次，导致无法正确删除 history。
https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/28fb147fcdc6208f0b3805f0f2b0ba72bdf97b4f/index.js#L374

**Comment by TBXark** [comment]
感谢反馈，已修复
