### ISSUE TITLE
接口报错问题

### ISSUE THREAD

**Issue by afa-1** [TBXark/ChatGPT-Telegram-Workers#152]
ERROR:CHAT: OpenAI API 错误
> You exceeded your current quota, please check your plan and billing details.
参数: {"model":"gpt-3.5-turbo","messages":{"role":"system","content":"你是一个得力的助手"},{"role":"user","content":"你好"}}

但我查询了账户余额，并没有超出，还剩很多

**Comment by erickyun** [comment]
> ERROR: CHAT: OpenAI API error
> 
> > You exceeded your current quota, please check your plan and billing details.  parameters: {"model":"gpt-3.5-turbo","messages":{"role":"system","content":"You are a powerful assistant"},{"role":"user","content":"Hello"}}
> 
> But I checked the account balance, and it didn't go over, there was a lot left

Where you able to fix this?
