### ISSUE TITLE
请向用户添加流式消息输出! 异步输出

### ISSUE THREAD

**Issue by tR4z8r** [TBXark/ChatGPT-Telegram-Workers#153]
请添加，以便机器人对用户的响应不会立即显示完整，而是慢慢地，逐字逐句！
谢谢！ 那太好了！

**Comment by Cheivin** [comment]
#93 这个在其他issue里面讨论过，屏幕跳动挺痛苦的

**Comment by TBXark** [comment]
因为不知道怎么计算cloudflare workers的CPU运算时间，考虑会导致可能CPU运算超时，大概率不会添加。

**Comment by tR4z8r** [comment]
显然很可悲! 我怎样才能在用户向机器人提出的每个问题后添加一条信息：等待......。

**Comment by tR4z8r** [comment]
另外，你能不能告诉我如何添加文本流输出，我非常感兴趣。感谢你们的辛勤工作!

**Comment by TBXark** [comment]
> 另外，你能不能告诉我如何添加文本流输出，我非常感兴趣。感谢你们的辛勤工作!

一直编辑那条消息往后面添加内容

**Comment by TBXark** [comment]
由于workers受限，你可以尝试我另外一个项目 https://github.com/TBXark/chat-bot-go。能简单的实现这个需求。
