### ISSUE TITLE
通过Actions自动部署Cloudflare，能否指定加密某个环境变量？

### ISSUE THREAD

**Issue by zwjie12** [TBXark/ChatGPT-Telegram-Workers#155]
第一次手动部署时，在workers环境变量中加密了API_KEY和TELEGRAM_AVAILABLE_TOKENS，但用Actions自动部署后，workers环境变量自动变成未加密状态了，能否实现自动部署也在workers中加密指定变量？

**Comment by TBXark** [comment]
https://developers.cloudflare.com/workers/platform/environments/ 官方目前没有给出类似的功能
