### ISSUE TITLE
响应慢，同时访问人数稍微多一点点就死机

### ISSUE THREAD

**Issue by xiaoyuer0408** [TBXark/ChatGPT-Telegram-Workers#156]
如题 请问有没有解决的方法 人数不超过20人就死机

**Comment by TBXark** [comment]
cloudflare同时相应20人肯定是没有问题呢，你说的这个同时是在群里同时有20个人在和他聊天吗

**Comment by xiaoyuer0408** [comment]
是的 在飞机群里 只要稍微多几个人同时提问就会卡死… 大佬还有别的方法可以快速响应和多人访问吗

**Comment by TBXark** [comment]
不好说这个是不是openai api卡住了

**Comment by TBXark** [comment]
可能是触发了bot 发送频率限制，dev分支telegram bot发送频率进行了优化
