### ISSUE TITLE
是否可以使用GPT-4？

### ISSUE THREAD

**Issue by KimLay233** [TBXark/ChatGPT-Telegram-Workers#162]
我已经购买了openAI plus，想试试能不能在TG上用GPT-4
我在js代码中修改了模型为gpt-4或者gpt4，但是都不行，机器人说

Error: OpenAI API Error
> The model gpt4 does not exist
or
Error: OpenAI API Error
> The model gpt-4 does not exist

**Comment by TBXark** [comment]
你的名字写错了，支持这个几个模型。`gpt-4`, `gpt-4-0314`, `gpt-4-32k`, `gpt-4-32k-0314`, `gpt-3.5-turbo`,` gpt-3.5-turbo-0301`。然后就是你得有gpt4 api的权限
