### ISSUE TITLE
[建议]增加自定义 api host，因为有的第三方比官方便宜很多

### ISSUE THREAD

**Issue by mithew** [TBXark/ChatGPT-Telegram-Workers#164]
![screenshot_20230419_132218](https://user-images.githubusercontent.com/43675269/232974887-86e34036-1132-4e36-bd12-3e65cf161a08.jpg)

类似这种，允许更换 api 网址

**Comment by TBXark** [comment]
现在就可以，配置 `OPENAI_API_DOMAIN ` 变量就行

**Comment by mithew** [comment]
好嘞
