### ISSUE TITLE
Distinguishable Font (1.5.0)

### ISSUE THREAD

**Issue by ehsrrr** [TBXark/ChatGPT-Telegram-Workers#168]
Hi dear TBXrak

In version 1.5.0, the fonts are inserted like this, is this a bug? When I click on the help command, they are not distinguishable.
![Screenshot 2023-04-21 223322](https://user-images.githubusercontent.com/130251049/233705013-8e73e6be-3e5f-4a1f-88bd-44ce69cf5dd3.png)

**Comment by MiracleXYZ** [comment]
I am experiencing the same issue where an unexpected line break appears at the beginning of my message. I believe this to be a bug.

**Comment by TBXark** [comment]
This is probably caused by me rendering with markdownv2 instead of markdown. Earlier, I was rendering with markdown.

**Comment by TBXark** [comment]
fixed
