### ISSUE TITLE
[BUG] bill数据错误

### ISSUE THREAD

**Issue by mingchau** [TBXark/ChatGPT-Telegram-Workers#169]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `1682088819` 
- sha: `2f3b9e9`
- branch: `master`

**描述问题**
`/bill`命令获取到的数据错误

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。
![image](https://user-images.githubusercontent.com/18564039/233768041-65a815f6-58c5-45eb-87a7-1987344d2e27.png)

**其他信息**
提供与问题相关的任何其他信息。

看了下代码，发现是起始日期的计算逻辑问题
默认`startDate`是90天之前的日期，如果`hard_limit_usd`设置>20，则`startDate`设置为当前月的1日。
这个逻辑有问题吧？

**Comment by TBXark** [comment]
这部分是参考了 https://github.com/ClarenceDan/openai-billing 的代码，逻辑可以优化一下。

**Comment by TBXark** [comment]
dev 中已经修改为当月账单
