### ISSUE TITLE
[BUG]Bot wont reply when asked about html codes

### ISSUE THREAD

**Issue by reonjy112** [TBXark/ChatGPT-Telegram-Workers#170]
Example input:
html code for login page

the bot only shows the loading text but wont reply with what was asked. happens only when asked for codes.

**Comment by reonjy112** [comment]
also, is there anyway to revert back to the default telegram font? i dont want to use the markdown.

**Comment by TBXark** [comment]
The default rendering method has been modified

**Comment by TBXark** [comment]
The failure of html to reply may be caused by rendering failure
