### ISSUE TITLE
[BUG]关于使用自动更新部署导致信息泄漏

### ISSUE THREAD

**Issue by Silentely** [TBXark/ChatGPT-Telegram-Workers#173]
Github Action自动更新中这一步
“CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} npm run wrangler publish --config=wrangler.toml”
会导致输出的log包含wrangler.toml明文信息

应包含个人信息没全截图 但是可以自己查看
![8ace6845c6aa80a893fcf52e31370860.jpg](https://img.mjj.today/2023/04/24/8ace6845c6aa80a893fcf52e31370860.jpg)

**Comment by TBXark** [comment]
thanks, 我尽快修复， 我先关闭这个issue。防止影响扩散
