### ISSUE TITLE
流式输出感觉没有之前那种方式流畅

### ISSUE THREAD

**Issue by Jv0id** [TBXark/ChatGPT-Telegram-Workers#174]
用telegram editMessageText API实现流式输出感觉没有之前那种方式流畅。
偶尔会出现卡顿的问题。
虽然内容都出来了，总感觉输出的内容方式怪怪的。

如果有个开关就好了。

以上纯属吐槽。

**Comment by TBXark** [comment]
有开关, 设置环境变量  `STREAM_MODE` 设置成 false

**Comment by Jv0id** [comment]
> 有开关, 设置环境变量 `STREAM_MODE` 设置成 false

明白了，感谢。
