### ISSUE TITLE
请问下是否支持gpt-4

### ISSUE THREAD

**Issue by Jv0id** [TBXark/ChatGPT-Telegram-Workers#175]
如题
请问下是否支持gpt-4模型？

**Comment by vicevolf** [comment]
支持的，我在用。设置下 CHAT_MODEL 就可以了…… 但是4目前比3.5贵30倍左右，用的时候要注意。

**Comment by Jv0id** [comment]
> 支持所有模型，前提是你有权限。然后是命名要对，现在支持的是下面几个。 gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301

好的，完美支持，谢谢。
