### ISSUE TITLE
[BUG]代码类问题总是过早中断回答

### ISSUE THREAD

**Issue by vicevolf** [TBXark/ChatGPT-Telegram-Workers#176]
**版本号**
当前已经是最新版本, 当前版本: {"ts":1682221130,"sha":"311c627"}

**描述问题**
让bot写“代码类”的问题时，bot的回复总会容易中断。

**复现问题**
重现问题的步骤：
如截图，随便问bot一个写一段代码的问题，总会早早中断回复。而其他文学创作等不会有此类问题。

**预期行为**
输出完整的回答。

**截图**
![Screenshot_2023-04-25-17-20-38-441_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/47265026/234233972-6e420753-4a40-4d20-903a-8de853877635.jpg)

**其他信息**
不能确定是OpenAI还是bot的问题。如中断时，是否是因为代码类问题输出的等待时间更长，导致bot中断了等。

**Comment by TBXark** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/9513891/234244906-df760682-52cd-4fec-a7e3-4fe4061d87c7.png">

大概率是超时了

**Comment by TBXark** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/9513891/234245160-3a89e2d4-13d1-416d-8f64-64d117dcf855.png">
大概率是超时了

**Comment by TBXark** [comment]
新的代码改了一下请求openai的时间。不过太长的还是会截断，你可以试一下。
