### ISSUE TITLE
[BUG] bot一直显示加载中

### ISSUE THREAD

**Issue by TomQuartz** [TBXark/ChatGPT-Telegram-Workers#178]
**版本号**
当前已经是最新版本, 当前版本: {"ts":1682221130,"sha":"311c627"}
- branch: master

**描述问题**
部署完成后bot一直回复加载中。运行init结果正常，开启DEBUG_MODE=true没有在KV里发现报错

**Comment by TBXark** [comment]
OpenAI API 现在好像有点问题
