### ISSUE TITLE
新代码报错

### ISSUE THREAD

**Issue by Silentely** [TBXark/ChatGPT-Telegram-Workers#18]
拆分后的新代码报错
[{"ok":false,"error_code":404,"description":"Not Found"}]

换回旧版无问题
[{"ok":true,"result":true,"description":"Webhook was set"}]

**Comment by TBXark** [comment]
是运行`init`报错了吗， 多少有点神奇，这块逻辑应该没有改变，这个错误时telegram返回的。要不试一下dev分支的代码？

**Comment by TBXark** [comment]
可是我用master分支的代码时正常的

**Comment by nofeetbird0321** [comment]
> WORKERS_DOMAIN

dev分支可以了，WORKERS_DOMAIN加https://了
