### ISSUE TITLE
配额

### ISSUE THREAD

**Issue by JDxiaojuju** [TBXark/ChatGPT-Telegram-Workers#186]
[在tg里/bill命令里面的用量，是指什么的？]

**Comment by TBXark** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/9513891/236974450-8c86024d-7e40-4ff5-bbf3-dd78d026ce03.png">
这个的数据

**Comment by JDxiaojuju** [comment]
> <img width="840" alt="image" src="https://user-images.githubusercontent.com/9513891/236974450-8c86024d-7e40-4ff5-bbf3-dd78d026ce03.png">
> 这个的数据

这个图是cloudflare里面的？

**Comment by TBXark** [comment]
openai 里的

**Comment by TBXark** [comment]
用完就没有了
________________________________
