### ISSUE TITLE
最后一步初始化打开网址失败

### ISSUE THREAD

**Issue by SIMPO18** [TBXark/ChatGPT-Telegram-Workers#19]
[{"ok":false,"error_code":404,"description":"Not Found"}]

**Comment by TBXark** [comment]
你可以试一下dev的init成功之后再切回master的代码

**Comment by SIMPO18** [comment]
> 是不是 `WORKERS_DOMAIN` 参数加了 `http` 协议头或者 `/` 后缀？

没有，就是workers_name.username.workers.dev这样的格式

**Comment by SIMPO18** [comment]
使用1.0.0版index.js代码成功了。

> 你可以试一下 dev 的 init 成功之后再切回 master 的代码

**Comment by nixiaoya** [comment]
> > 不是的，应该是因为更新了新版代码后没有把variable name全部加上去，我刚刚解决了这个问题
> 
> 我刚才更新新版 master 分支代码后，发消息没反应，回滚到旧版是正常的，看来得试试把参数都加上。

按最新文档，更新参数配置后，运行正常。

**Comment by hubeiqiao** [comment]
[{"ok":false,"error_code":404,"description":"Not Found"}]

我也遇到了相同的问题，使用的是 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js 中的内容。

**Comment by TBXark** [comment]
> [{"ok":false,"error_code":404,"description":"Not Found"}]
> 
> 我也遇到了相同的问题，使用的是 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js 中的内容。

用 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/d79c67f7167b31b3a28914cf33e737ce4ee39082/index.js 的版本先初始化试一下

**Comment by hubeiqiao** [comment]
> > [{"ok":false,"error_code":404,"description":"Not Found"}]
> > 我也遇到了相同的问题，使用的是 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js 中的内容。
> 
> 用 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/d79c67f7167b31b3a28914cf33e737ce4ee39082/index.js 的版本先初始化试一下

可以了，感谢！
