### ISSUE TITLE
你好，这样是action启用了吗？

### ISSUE THREAD

**Issue by bilibili2233a** [TBXark/ChatGPT-Telegram-Workers#194]
用了很久，还是不会更新，
![Screenshot_20230514_211139_com.github.android.jpg](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/99982054/e5ba550e-d5a8-4b14-b1a0-6e98c07bddb4)

好像不对，是不是这个action？
![Screenshot_20230514_211535_com.android.browser.jpg](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/99982054/98104e9d-2ebc-406f-a6a1-0c5c52ad91c3)

**Comment by TBXark** [comment]
看样子是没有启动

**Comment by bilibili2233a** [comment]
啊这，为什么自动更新还是失败了😢

![Screenshot_20230515_120343_com.android.browser.jpg](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/99982054/c41098bd-14e8-4f06-b169-6ed1e75c2e5a)

这样填的：
![Notepad_202305151206_01557_edit_57871330008356.png](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/99982054/a9f230b6-4c6e-4abd-91b9-d50b9ff080b0)

**Comment by TBXark** [comment]
CLOUDFLARE_API_TOKEN 错了吧
