### ISSUE TITLE
[建议]建议加入非官方API调用的功能

### ISSUE THREAD

**Issue by NiuHK** [TBXark/ChatGPT-Telegram-Workers#198]
OpenAi开放了ChatGPT 3.5的接口，但是是要算token，一个账号只有18美元的试用。GitHub上
有ChatGPT网页版的逆向API，经测试是完全免费的。
是否可以考登陆网页版的非官方API？

**Comment by TBXark** [comment]
现在是可以自定义API域名 #164。但是逆向web的API差异比较大展示不支持。
