### ISSUE TITLE
适配一下Azure OpenAI

### ISSUE THREAD

**Issue by C018** [TBXark/ChatGPT-Telegram-Workers#199]
rt

**Comment by diciky** [comment]
希望大佬能适配Azure OpenAI.目前网页访问openai各大机场已经团灭了

**Comment by TBXark** [comment]
DEV添加了Azure OpenAI 支持。目前只支持聊天，账单和图片生成不支持。需要添加两个字段

|key|value|
|--|---|
|AZURE_API_KEY |`两个密钥随便选一个就可以`|
| AZURE_COMPLETIONS_AP |`https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=2023-05-15`|

**Comment by diciky** [comment]
谢谢巨佬

**Comment by diciky** [comment]
报错Error: Cannot read properties of undefined (reading '0')

**Comment by TBXark** [comment]
> 报错Error: Cannot read properties of undefined (reading '0')

API 格式错了，你按我写的格式写。结尾是 `/chat/completions`

**Comment by diciky** [comment]
发现问题了.格式没错,按你写的.key少了个字母,应该是AZURE_COMPLETIONS_API

**Comment by TBXark** [comment]
> 发现问题了.格式没错,按你写的.key少了个字母,应该是AZURE_COMPLETIONS_API
😂😂😂
