### ISSUE TITLE
一直报“我不知道该怎么回答”

### ISSUE THREAD

**Issue by Tsai002** [TBXark/ChatGPT-Telegram-Workers#2]
"logs": [
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading '0')"
      ],
      "level": "error",
      "timestamp": 1677838109994
    }
  ],

**Comment by Cheivin** [comment]
`msgCreateNewChatContext`中把判断改一下就可以了。
```
  if (message.text !== '/new' ||  message.text !== '/start') {
    return null;
  }
```
改成
```
  if (message.text !== '/new' &&  message.text !== '/start') {
    return null;
  }
```

**Comment by Kkirsii** [comment]
我也是

**Comment by ipez** [comment]
官方api正常，今天换了chimera api出了同样的问题
Error: Cannot read properties of undefined (reading '0')
