### ISSUE TITLE
[BUG] Add or change language

### ISSUE THREAD

**Issue by chaveamin** [TBXark/ChatGPT-Telegram-Workers#201]
Ver: **eb7c605**

**描述问题**
How to change the language or add one

I want to add another language or if it's possible change the current language(bot commands language)
![1](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/78597787/533b0d2a-7ec5-4b50-b392-cf39d889f2e1)

Please response in english, Thanks

**Comment by TBXark** [comment]
You can add an environment variable configuration to cloudflare, set `LANGUAGE` to `en`. then re-invoke the init excuse
