### ISSUE TITLE
在workers里部署好之后进行初始化提示Webhook is already set且机器人无响应

### ISSUE THREAD

**Issue by qq1737333652** [TBXark/ChatGPT-Telegram-Workers#21]
我按照部署流程部署了worker,当我进行到
六. 初始化
运行 https://workers_name.username.workers.dev/init 绑定telegram时提示
[{"ok":true,"result":true,"description":"Webhook is already set"}]
并且给机器人发消息也没有反应

**Comment by TBXark** [comment]
可以使用最新的`master`分支的代码了
