### ISSUE TITLE
[问题] Error: Invalid header value

### ISSUE THREAD

**Issue by butty0** [TBXark/ChatGPT-Telegram-Workers#211]
采用  https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js
按照  科技小白唐部署-https://www.youtube.com/watch?v=BvxrZ3WMrLE

出现
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/141322104/ba9b1ac0-1dd9-467c-b111-8ad6b7030818)

真心求教！！！

**Comment by TBXark** [comment]
我试了一下最新的代码没有啥问题呢，必须的环境变量都添加了吗？
