### ISSUE TITLE
群组里面不回复

### ISSUE THREAD

**Issue by Xuan20236** [tbxark/ChatGPT-Telegram-Workers#212]
求大佬帮我看看，我这样设置的环境变量是否有问题，群组ID已经写进白名单里面了，已添加机器人为管理员，也从BotFather里面关掉了隐私模式，私聊是可以正常回复的![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/132374679/e745e9a3-058e-4f23-a0a0-c363f9adaae4)

**Comment by TBXark** [comment]
你和他说话的时候 @ 机器人了吗

**Comment by Xuan20236** [comment]
> 你和他说话的时候 @ 机器人了吗

@了，也没有回复
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/132374679/e8874ce9-3475-41e4-a6ae-78dae6bf3ae4)

**Comment by Xuan20236** [comment]
@了，也没有回复
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/132374679/cb8ed1db-8024-4423-bba2-045cdeb1b85e)

**Comment by Xuan20236** [comment]
> 你和他说话的时候 @ 机器人了吗

@了，也没有回复
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/132374679/d24c8387-5b3c-4c54-b89b-f6f8a3760951)

**Comment by Xuan20236** [comment]
> 你和他说话的时候 @ 机器人了吗

是不是跟我没有写 TELEGRAM_BOT_NAME 变量有关系？这个变量我看帮助文档没看明白（
帮助文档写的是跟前面名字顺序一样，那是跟 TELEGRAM_AVAILABLE_TOKENS 保持一样还是填写 xxx_bot 之后跟上token啊，能否给个实例呢，谢谢

**Comment by tbxark** [comment]
是 按顺序对于bot。 

TELEGRAM_AVAILABLE_TOKENS: token1,token2
TELEGRAM_BOT_NAME： xxx1_bot, xxx2_bot,

**Comment by Xuan20236** [comment]
> 是 按顺序对应bot。
> 
> TELEGRAM_AVAILABLE_TOKENS: token1,token2 TELEGRAM_BOT_NAME： xxx1_bot, xxx2_bot,

这里是填机器人的用户名还是机器人的名字？

**Comment by Xuan20236** [comment]
谢谢，填上机器人用户名就可以用了

> 是 按顺序对应bot。
> 
> TELEGRAM_AVAILABLE_TOKENS: token1,token2 TELEGRAM_BOT_NAME： xxx1_bot, xxx2_bot,

谢谢，填上机器人用户名就可以用了
