### ISSUE TITLE
请教群组机器人设置

### ISSUE THREAD

**Issue by xiangyingchang** [TBXark/ChatGPT-Telegram-Workers#213]
非常感谢教程，完全不懂代码，也部署成功了，但是在群组设置上遇到了困难

**描述问题**
按照配置设置了群主机器人后，在群里机器人仍无反应，不知道是否方便帮忙看看哪里出了问题，感谢

**截图**
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/10992221/8983ad65-7da2-4445-a582-81e4c29835df)

**Comment by xiangyingchang** [comment]
刷新后解决了

**Comment by TBXark** [comment]
可以参考 https://github.com/TBXark/ChatGPT-Telegram-Workers/discussions/122
