### ISSUE TITLE
Hope to support the call of Azure OpenAI. 

### ISSUE THREAD

**Issue by xiangyingchang** [TBXark/ChatGPT-Telegram-Workers#214]
Microsoft has supported the OpenAI interface today. Compared to ChatGPT, Microsoft currently does not restrict its usage region and can be used anywhere, making it more flexible. Here is an introduction: https://learn.microsoft.com/zh-cn/azure/ai-services/openai/overview

**Comment by TBXark** [comment]
已经支持了具体配置可以参考 #199
