### ISSUE TITLE
[BUG]最近在使用机器人过程中发现有些字符会显示不出来，用？代替

### ISSUE THREAD

**Issue by xiangyingchang** [TBXark/ChatGPT-Telegram-Workers#216]
用的最新的代码部署的，使用微软的gpt4模型，截图如下，直觉上是显示兼容问题
![Uploading IMG_2115.jpeg…]()

**Comment by TBXark** [comment]
图没有传成功，是一直都会这样吗，可能是流模式的时候刚好解析了半个字符吧。

**Comment by xiangyingchang** [comment]
不好意思没传成功，偶尔会出现：
![IMG_2115](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/10992221/f5b85166-bded-4312-89bb-53553f205fc4)

**Comment by TBXark** [comment]
应该是下面这段代码读取流数据的时候啊给你更好分割了中文字符
```js
data = await reader.readAtLeast(4096, new Uint8Array(5000));
pendingText += decoder.decode(data.value);
```

**Comment by TBXark** [comment]
dev分支换了openai官方的解析器，应该没有问题了

**Comment by TBXark** [comment]
<img width="636" alt="image" src="https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/9513891/3a81ff09-e555-46a0-b38d-cf4f413179a8">

**Comment by xiangyingchang** [comment]
> dev分支换了openai官方的解析器，应该没有问题了

非常感谢，我去重新部署下

**Comment by xiangyingchang** [comment]
> dev分支换了openai官方的解析器，应该没有问题了

我直接替换了js文件，发现没有用，是操作不对么？

**Comment by TBXark** [comment]
具体怎么复现出来？

**Comment by xiangyingchang** [comment]
> 具体怎么复现出来？

下午尝试了好多次，没有再复现了，后面有问题再来麻烦你，感谢！

**Comment by xiangyingchang** [comment]
复现这个问题了：

让GPT基于以下内容写一篇小红书文案：
Norway 🇳🇴

The top of the Reinebringen Mountain is one of the most popular places on the Lofoten Islands. It is from here that most of the "classic" panoramic photos of Lofotens were taken with views of the archipelago, the fishing harbor, mountain lakes, the Rheinefjord and the picturesque town of Rheine.

Rheinebringen has several peaks, and "panoramic" is not the highest of them. The final point of the route is at a relatively low altitude of 448 meters, but because of the steep ascent, the ascent does not seem like an easy walk.

输出如下：

![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/10992221/98e9d59e-69f0-47d8-933e-bf7bc88ba4ab)

**Comment by xiangyingchang** [comment]
哈哈哈，搞不懂了，不过这个还好，至少不影响整体使用。
但上一个issue中讨论的持续loading问题，有点严重，如果方便的话辛苦帮忙看看，麻烦了
