### ISSUE TITLE
[建议] 可否增加网页版中的“Custom Instructions”功能

### ISSUE THREAD

**Issue by Mjmaster** [TBXark/ChatGPT-Telegram-Workers#221]
github上有些写得很不错的prompt script可用于网页版的Custom Instructions，可否也添加一个参数可以使用Custom Instructions

**Comment by TBXark** [comment]
`github上有些写得很不错的prompt script`是啥，有repo吗给点参考

**Comment by Mjmaster** [comment]
比如这个 https://github.com/ProfSynapse/Synapse_CoR/blob/main/prompt.txt
把文本直接粘贴到网页版的Custom Instructions里就行了。然后我把这段代码贴到Chrome的chathub扩展里的System Message里也有效。

**Comment by TBXark** [comment]
这个应该是相当于API里的system message, 你使用现在这个`/setenv SYSTEM_INIT_MESSAGE=现在开始你是喵娘，每句话以喵结尾`就可以了

**Comment by Mjmaster** [comment]
用了/setenv SYSTEM_INIT_MESSAGE= 可以了，谢谢！是每次用的时候都要打一下这个命令吗？

**Comment by TBXark** [comment]
> 用了/setenv SYSTEM_INIT_MESSAGE= 可以了，谢谢！是每次用的时候都要打一下这个命令吗？ 我刚才试了下，在workers里Variables里的SYSTEM_INIT_MESSAGE粘贴进去无效。只能通过/setenv SYSTEM_INIT_MESSAGE=

这好像是个BUG，我改一下，应该就有用了。。。

**Comment by TBXark** [comment]
> 用了/setenv SYSTEM_INIT_MESSAGE= 可以了，谢谢！是每次用的时候都要打一下这个命令吗？ 我刚才试了下，在workers里Variables里的SYSTEM_INIT_MESSAGE粘贴进去无效。只能通过/setenv SYSTEM_INIT_MESSAGE=

dev分支已修复

**Comment by Mjmaster** [comment]
感谢！
