### ISSUE TITLE
能否支持oneapi这样的第三方key和api的调用，以及百度讯飞等支持

### ISSUE THREAD

**Issue by dadaoerv** [TBXark/ChatGPT-Telegram-Workers#227]
大佬辛苦，已经支持了第三方api的域名，但是还是要调用openai的key
对于已经集成了多语言模型的oneapi，能否支持一下。

key是中转或者自己搭建的
地址是自己的oneapi地址。

**Comment by TBXark** [comment]
支持，只要是API兼容Openai的就可以只要设置 `OPENAI_API_DOMAIN ` 环境变量即可
