### ISSUE TITLE
请问如果使用Cloudflare 的WORKER AI?

### ISSUE THREAD

**Issue by burndown** [TBXark/ChatGPT-Telegram-Workers#228]
Worker 里已经加上变量了，AI Binding也加上了，怎么设置使用这个llama2 7b？
chat_MODEL 直接修改成@cf/meta/llama-2-7b-chat-int8 好像不管用，也没有看到其他地方的开关。

> WORKERS_AI_MODEL | @cf/meta/llama-2-7b-chat-int8

Variable name |  
-- | --
AI | Workers AI Catalog

**Comment by TBXark** [comment]
名字设置对了应该可以，具体支持模型列表可以看
https://developers.cloudflare.com/workers-ai/models/text-generation/

**Comment by burndown** [comment]
> 名字设置对了应该可以，具体支持模型列表可以看 https://developers.cloudflare.com/workers-ai/models/text-generation/

WORKERS_AI_MODEL 设置了，AI 绑定了，还需要设置CHAT_MODEL么？

**Comment by burndown** [comment]
搞定了，把变量里，openai的key 和 chat model删了就好了。多谢开发者
