### ISSUE TITLE
没有授权怎么解决

### ISSUE THREAD

**Issue by ksewin** [TBXark/ChatGPT-Telegram-Workers#23]
"webhook":{"ok":false,"error_code":401,"description":"Unauthorized"},"command":{"ok":false,"error_code":401,"description":"Unauthorized"}

**Comment by informationcrazy** [comment]
webhook":{"ok":false,"error_code":400,"description":"Bad Request: bad webhook: Failed to resolve host: No address associated with hostname"},"command":{"ok":true,"result":true 我的是这样的

**Comment by TBXark** [comment]
@informationcrazy @ksewin  可以截图看一下环境变量的配置吗 稍微码一下敏感内容

**Comment by TBXark** [comment]
@informationcrazy @ksewin 试一试dev分支新编译的版本？

**Comment by Xmaspro** [comment]
> "webhook":{"ok":false,"error_code":401,"description":"Unauthorized"},"command":{"ok":false,"error_code":401,"description":"Unauthorized"}

我也碰到这个问题，建议检查cloudflare worker的variable设置：
      - TELEGRAM_AVAILABLE_TOKENS：是10位数字+一串字符（我开始没把数字输进去）

**Comment by TBXark** [comment]
完整的TOKEN是这样的 数字加冒号加乱码
```
0714174624:AAGiUJ_y2C07GBIN_yCcjy4dnj-K2NDu_Yw
```

新版代码可以不用设置`WORKERS_DOMAIN ` 但是要设置的话是长这样的, 没有`https://`, 结尾没有 `/`
```
aaa.bbb.workers.dev
```

**Comment by ksewin** [comment]
> @informationcrazy @ksewin  可以截图看一下环境变量的配置吗 稍微码一下敏感内容

![Screenshot_20230307_153902.jpg](https://user-images.githubusercontent.com/59649563/223355913-e36367fd-cf60-45f7-aab9-decdf3984de4.jpg)

这样的

**Comment by houhoz** [comment]
我也是这样。。怎么解决呢
```
Bot ID: 6296922595
Webhook: {"ok":false,"error_code":404,"description":"Not Found"}

Command: {"ok":false,"error_code":404,"description":"Not Found"}
```
<img width="771" alt="image" src="https://user-images.githubusercontent.com/19684376/223674869-64b3550e-ea22-4692-94e5-4bcaf602b57a.png">
