### ISSUE TITLE
[BUG]ERROR: Cannot read properties of undefined (reading 'delta')

### ISSUE THREAD

**Issue by zyjia** [TBXark/ChatGPT-Telegram-Workers#233]
使用的是最新的代码部署在cloudflare,无论是使用代理azure模式(模拟openai)还是直接指定azure模式均返回ERROR: Cannot read properties of undefined (reading 'delta')

**Comment by TBXark** [comment]
版本号是什么，试一下最新dev分支的版本看看应该会有不一样的报错

**Comment by zyjia** [comment]
> 版本号是什么，试一下最新dev分支的版本看看应该会有不一样的报错

今天试了，还是一样的问题，我确认api接口没有问题，在apifox和postman中调用都可以正确返回

**Comment by TBXark** [comment]
只有这个地方读了delta，但是dev分支已经加了可选判断，按理说不会`undefined`，除非连`data`也是空
https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/6f292617bad3ec1accefe8ff39ff5bb5bfb2bb2c/src/openai.js#L107

**Comment by TBXark** [comment]
不过如果data是null，那么报错应该会变成`TypeError: Cannot read properties of null (reading 'choices')`

**Comment by zyjia** [comment]
下面是api调用返回的数据 
data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant"},"content_filter_results":{}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":"Hello"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":"!"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" How"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" can"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" I"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" assist"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" you"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":" today"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":null,"index":0,"delta":{"content":"?"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"id":"chatcmpl-8mu3YaOsM96g9zbk5J3Bftu0bBVdp","object":"chat.completion.chunk","created":1706665916,"model":"gpt-4-32k","choices":[{"finish_reason":"stop","index":0,"delta":{},"content_filter_results":{}}]}

data: [DONE]

**Comment by TBXark** [comment]
😂 复现不出来

<img width="569" alt="image" src="https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/9513891/2dd930ee-17b6-4867-af38-f5aadd30ce41">

**Comment by cpedia** [comment]
我也遇到了同样的问题，我设置了AI_PROVIDER为azure.

**Comment by cpedia** [comment]
不过我的报错是：

        "TypeError: Cannot read properties of null (reading 'USER_DEFINE')"

**Comment by TBXark** [comment]
> 不过我的报错是：
> 
> ```
>     "TypeError: Cannot read properties of null (reading 'USER_DEFINE')"
> ```

9acef355  dev分支改了一下，你试一下这个版本
