### ISSUE TITLE
[Feature]  image generation and text generation use different AI providers

### ISSUE THREAD

**Issue by rtromp4** [TBXark/ChatGPT-Telegram-Workers#235]
I want to use chatgpt unofficial api for text generation and cloudflare for image gen... How to do it/?

**Comment by TBXark** [comment]
Do you mean that image generation and text generation use different AI providers?

**Comment by rtromp4** [comment]
Yes... (For text i will use my own bingai (works fine with ur code  @Imagegenbot009bot and for image i will use cloudflares model)

**Comment by TBXark** [comment]
This configuration is not available at the moment, but you can modify the code `loadImageGen ` to only return `requestImageFromWorkersAI ` 

https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/edd85ae22bcc97baf89e26b2c097a64d1748d73f/src/llm.js#L136-L154

**Comment by rtromp4** [comment]
Problem solved 🎇
