### ISSUE TITLE
每次都发上下文，token会消耗过快吗

### ISSUE THREAD

**Issue by daizy008** [TBXark/ChatGPT-Telegram-Workers#24]
有没有办法把之前发过的消息暂存在某个动态的链接。让api读取。减少token消耗

**Comment by TBXark** [comment]
chatgpt没有访问网络能力，目前看文档就是这么实现的。

**Comment by daizy008** [comment]
但事实上，他可以根据url总结文章嘞。（mp.weixin除外）

TBXark ***@***.***>于2023年3月7日 周二上午7:57写道：

**Comment by TBXark** [comment]
好像是可以。👍

**Comment by TBXark** [comment]
![image](https://user-images.githubusercontent.com/9513891/223313303-d7b61d05-b8b2-4285-91f7-93ec2b24e800.png)

**Comment by daizy008** [comment]
部分新闻网站可以。甚至可以翻过paywall总结内容

TBXark ***@***.***>于2023年3月7日 周二上午11:29写道：

**Comment by TBXark** [comment]
![image](https://user-images.githubusercontent.com/9513891/223317871-173d7586-d396-4b5c-8b3c-cda22bbd6a64.jpeg)

实际上是瞎扯 不过大网站数据多可能推断的比较好

**Comment by CCCAUCHY** [comment]
为什么要发送上下文，我记得好像有会话ID来着
