### ISSUE TITLE
CF模型 /img bot只显示一段时间正在发送图片但不输出

### ISSUE THREAD

**Issue by Morris-Lucifer** [TBXark/ChatGPT-Telegram-Workers#241]
**版本号**
  // 当前版本
  BUILD_TIMESTAMP = 1707027852;
  // 当前版本 commit id
  BUILD_VERSION = "4d3903e";
  BRANCH=master

**描述问题**
设置了cloudflare workers ai画图模型参数，输入 `/img 狸花猫` ，但是bot只显示一段时间正在发送图片，然后没有输出

`WORKERS_IMAGE_MODEL = @cf/stabilityai/stable-diffusion-xl-base-1.0`

**Comment by Morris-Lucifer** [comment]
可能是cf的问题？我直接curl调用也报错
{"errors":[{"message":"Error: unexpected type \"int32\" with value \"undefined\".","code":1000}],"success":false,"result":{},"messages":[]}

**Comment by TBXark** [comment]
试一试换这个model： `@cf/microsoft/resnet-50`

**Comment by Morris-Lucifer** [comment]
> @cf/microsoft/resnet-50

这是图像分类模型吧，我想试试文本生成图像的模型。。

**Comment by TBXark** [comment]
🤦 哦对哦，我看错了

**Comment by TBXark** [comment]
你有没有修改过环境变量？之前有个BUG，修改环境变量之后可能没有生效，dev新版修改了一下这个逻辑

**Comment by Morris-Lucifer** [comment]
> 你有没有修改过环境变量？之前有个BUG，修改环境变量之后可能没有生效，dev新版修改了一下这个逻辑

您说的是/setenv吗？我之前好像确实用过这个，但是那个时候好像还不支持cf AI，当时是用来配置chatgpt的角色定义和temperature。后来改成cf AI之后没有动过之前的配置，只删除了openai相关的API_KEY和CHAT_MODEL。

不过我现在改用coze的bot绑定了，就不麻烦作者debug了：）
