### ISSUE TITLE
Error: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by SUGARYeUNGG** [TBXark/ChatGPT-Telegram-Workers#244]
Error: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
有OpenAI的账号，在与机器人对话时，为什么会显示这个提示呢，是因为默认模型的问题吗？ Chat 3.5 turbo ,
可以通过更换模型解决这个问题吗？

我是免费用户，没有购买订阅，没有ChatGPT 4

**Comment by foreveruand** [comment]
免费用户没有api额度
