### ISSUE TITLE
[BUG] Cannot generate image by Azure DALL-E 3 while ai provider is not specified azure

### ISSUE THREAD

**Issue by youngzyl** [TBXark/ChatGPT-Telegram-Workers#248]
**版本号**
- ts: `1715327121`
- sha: `8d6f441`
- branch: `master`

**描述问题**
变量AI Provider设定为Workers或的时候，函数requestImageFromOpenAI只会向OpenAI发起DallE请求。

**预期行为**
requestImageFromOpenAI中判断isAzureModel的时候是否应该根据AI_IMAGE_PROVIDER而不是AI_PROVIDER。

**截图**
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/35056356/5b513766-b5ac-4311-b119-9790d68308f6)
![image](https://github.com/TBXark/ChatGPT-Telegram-Workers/assets/35056356/1fa8badf-09b0-4a61-87dd-7833e760242b)

**其他信息**
把const provider = context.USER_CONFIG.AI_IMAGE_PROVIDER;并且定义AI_IMAGE_PROVIDER为azure就没问题了

**Comment by TBXark** [comment]
确实 加字段的时候忘记 已在dev更新
