### ISSUE TITLE
对话没有回复咋整？

### ISSUE THREAD

**Issue by bhj128128** [TBXark/ChatGPT-Telegram-Workers#25]
如题。

**Comment by TBXark** [comment]
先运行 init 接口

**Comment by Guojingxing** [comment]
怎么运行 init 接口

**Comment by TBXark** [comment]
![image](https://user-images.githubusercontent.com/9513891/223295546-a67e590d-504f-4a4e-9861-c516675d565d.jpeg)

打开你的workers就可以了

**Comment by Xmaspro** [comment]
![Screenshot 2023-03-07 at 11 42 03](https://user-images.githubusercontent.com/61029176/223315239-3384c541-d1f3-43c7-8a5a-efc7ad5a13b7.jpg)
运行init后提示如上，请问是什么原因？

**Comment by TBXark** [comment]
@Xmaspro 试一试dev分支编译的版本

**Comment by damozhang** [comment]
> @Xmaspro 试一试dev分支编译的版本

两个分支执行 init 结果都是
```
Webhook: {"ok":false,"error_code":404,"description":"Not Found"}

Command: {"ok":false,"error_code":404,"description":"Not Found"}
```

**Comment by XueshiQiao** [comment]
@damozhang 我也遇到了这个问题，设置参数时， TELEGRAM_AVAILABLE_TOKENS  改为 TELEGRAM_TOKEN

参考： https://github.com/TBXark/ChatGPT-Telegram-Workers/issues/65

**Comment by damozhang** [comment]
@XueshiQiao 我把 TELEGRAM_AVAILABLE_TOKENS 改为 TELEGRAM_TOKEN 后也无法工作。

添加 TELEGRAM_BOT_NAME 后，问题解决了。

**Comment by roamdog** [comment]
> @XueshiQiao 我把 TELEGRAM_AVAILABLE_TOKENS 改为 TELEGRAM_TOKEN 后也无法工作。
> 
> 添加 TELEGRAM_BOT_NAME 后，问题解决了。

同样操作，解决了。

**Comment by TBXark** [comment]
> 

你这个是群聊里面没有反应吧

**Comment by shadoway11** [comment]
![IMG_3490](https://user-images.githubusercontent.com/62317095/224108171-e323ad0f-ef37-419d-96d6-4250cf2850a1.jpeg)
我在“click here”后出现这个情况，与机器人对话没有反应，尝试添加telegram_bot_name也没用

**Comment by bhj128128** [comment]
可以了，谢谢！
