### ISSUE TITLE
[BUG]无法设置第三方api

### ISSUE THREAD

**Issue by sandyplus** [TBXark/ChatGPT-Telegram-Workers#266]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`
- branch: `当前代码所在的分支`
 // 当前版本
  BUILD_TIMESTAMP = 1721280807;
  // 当前版本 commit id
  BUILD_VERSION = "8aa40ac";
UPDATE_BRANCH = "master"

**描述问题**
无论如何，都无法设置第三方api，设置好了依然报错，但同样的设置在chatbox中正常。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。
![image](https://github.com/user-attachments/assets/9a85f698-1cdd-4ede-a2a9-9d7937d87c0d)

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
1. 你可以在手动环境变量中配置`OPENAI_API_BASE`这个字段, 
2. 或者你还是想通过命令修改这个字段的话
 -  你可以手动删除代码中`LOCK_USER_CONFIG_KEYS` 中的  `OPENAI_API_BASE `
 -  或者设置`LOCK_USER_CONFIG_KEYS ` 为空字符串，这样就不会锁定任何字段不给修改，

**Comment by TBXark** [comment]
本来这个字段这个目的是防止开放bot给其他人使用的时候，其他人通过修改`OPENAI_API_BASE `到一个恶意的API导致key泄露。所以默认值包含了所有API BASE URL。

**Comment by sandyplus** [comment]
> 1. 你可以在手动环境变量中配置`OPENAI_API_BASE`这个字段,
> 2. 或者你还是想通过命令修改这个字段的话
> 
> * 你可以手动删除代码中`LOCK_USER_CONFIG_KEYS` 中的  `OPENAI_API_BASE `
> * 或者环境变量中设置`LOCK_USER_CONFIG_KEYS ` 为空字符串，这样就不会锁定任何字段不给修改，

谢谢，已经设置好了。还有一个问题，是不是chat model无法解释图片或文件（如PDF）：
![image](https://github.com/user-attachments/assets/bd173e36-f45b-425e-b91e-1a2a160be7f7)

**Comment by TBXark** [comment]
暂时还实现多模态的功能
