### ISSUE TITLE
[BUG]请问一下大佬，想调整 temperature 要如何操作？  

### ISSUE THREAD

**Issue by xyxgogo** [TBXark/ChatGPT-Telegram-Workers#267]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`
- branch: `当前代码所在的分支`

**描述问题**
简要而清晰地解释问题。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。

**其他信息**
提供与问题相关的任何其他信息。

**Comment by TBXark** [comment]
设置`OPENAI_API_EXTRA_PARAMS `环境变量，`OPENAI_API_EXTRA_PARAMS ` 是一个字符串的Json，
比如 设置 `OPENAI_API_EXTRA_PARAMS={"temperature":0.5}`

**Comment by xyxgogo** [comment]
谢谢 设置方法是不是增加一个变量  OPENAI_API_EXTRA_PARAMS    值填：    {"temperature":0.5}    ？   另外想问一下，如果不增加则会个变量，默认的  temperature 值是多少？       另外，同理的可设置的 值还有哪些？   谢谢你！

**Comment by TBXark** [comment]
默认就是null，按照openai的文档null的话就是1。

**Comment by xyxgogo** [comment]
感谢！！
