### ISSUE TITLE
现在cloudflare是不是关闭了新建workers?

### ISSUE THREAD

**Issue by dangerboy1986** [TBXark/ChatGPT-Telegram-Workers#27]
![image](https://user-images.githubusercontent.com/37978383/223305875-800c2f76-06b1-4612-b59a-eabdf0733ae1.png)

我在右上角找不到这个选项了。

**Comment by TBXark** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/9513891/223313828-12aebdf9-25a8-414b-9b37-26708e9202e1.png">
