### ISSUE TITLE
[BUG]无法进行群聊

### ISSUE THREAD

**Issue by huawuhen** [TBXark/ChatGPT-Telegram-Workers#272]
已配置变量：
TELEGRAM_BOT_NAME: xxx_bot
TELEGRAM_AVAILABLE_TOKENS:9233894:ksjrienixxxxx
GROUP_CHAT_BOT_ENABLE:true
CHAT_WHITE_LIST:912831
CHAT_GROUP_WHITE_LIST:1087968825,1002128923508

报错如下：
AT机器对话，返回
> Your group are not in the white list, please contact the administrator to add you to the white list .Your chat_id-1002128923508

**Comment by TBXark** [comment]
群聊的ID是带负号的

**Comment by huawuhen** [comment]
> 群聊的ID是带负号的

是我获取的群聊ID不对，还是前面少一个-

**Comment by TBXark** [comment]
> > 群聊的ID是带负号的
> 
> 是我获取的群聊ID不对，还是前面少一个-

Your group are not in the white list, please contact the administrator to add you to the white list .Your chat_id**-1002128923508**

你这里不是有负号么，是你环境变量里没写

**Comment by huawuhen** [comment]
> > > 群聊的ID是带负号的
> > 
> > 
> > 是我获取的群聊ID不对，还是前面少一个-
> 
> Your group are not in the white list, please contact the administrator to add you to the white list .Your chat_id**-1002128923508**
> 
> 你这里不是有负号么，是你环境变量里没写

非常感谢
