### ISSUE TITLE
[BUG] Cloudflare 多个可用账户时 Github Action 自动更新流程会报错

### ISSUE THREAD

**Issue by djx30103** [TBXark/ChatGPT-Telegram-Workers#275]
![1](https://github.com/user-attachments/assets/bca75080-72e9-45fb-99c8-54e73671644d)

并且`wrangler publish` 已弃用，将在下次主要版本中删除。

**Comment by TBXark** [comment]
- 创建token的时候不选全部用户应该可以避免这个问题
- Github Action 已更新

<img width="619" alt="image" src="https://github.com/user-attachments/assets/72d1d0f6-98b3-4edd-aa83-eeee0c1fb219">

**Comment by djx30103** [comment]
https://github.com/cloudflare/workers-sdk/issues/6466
会考虑通过添加 CLOUDFLARE_ACCOUNT_ID 作为环境变量解决这个问题吗？

**Comment by TBXark** [comment]
那其实在WRANGLER_TOML中的完整toml配置中添加account_id就可以解决了
<img width="720" alt="image" src="https://github.com/user-attachments/assets/1a36cc3a-38f8-4d9d-b06d-1edc30ebfd2f">

**Comment by djx30103** [comment]
因为管理多个token挺麻烦的，所以我都是包含所有账户的，谢咯哈
