### ISSUE TITLE
实时数据流传输

### ISSUE THREAD

**Issue by Qchsi** [TBXark/ChatGPT-Telegram-Workers#28]
telegram机器人能否通过ChatGPT API SSE，实现实时数据流传输，就像网页版那样的效果。quora的poe这个软件就可以，而且响应速度极快

**Comment by TBXark** [comment]
已经开放这个API了么，不过tg的api不支持流，还得的到完整数据才能返回

**Comment by Qchsi** [comment]
> 

具体的技术我不懂啊，一开始我就希望弄个tg机器人，看你的教程实现了，非常感谢🙏

**Comment by Cheivin** [comment]
暂时没发现tg有流的api，如果新增了或者是我们漏掉了，欢迎提供相关文档地址
