### ISSUE TITLE
【询问】“添加插件系统” 的更新  在哪里配置？  

### ISSUE THREAD

**Issue by xyxgogo** [TBXark/ChatGPT-Telegram-Workers#281]
文档中没找到

**Comment by TBXark** [comment]
https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/plugins/README_CN.md 单独的文档

**Comment by xyxgogo** [comment]
谢谢。  这个方向很有想象空间。 看未来能插件一些什么特别的功能了
