### ISSUE TITLE
[BUG] 疑似被未授权telegram用户使用

### ISSUE THREAD

**Issue by jinjunliu** [TBXark/ChatGPT-Telegram-Workers#289]
**版本号**
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `9/4/2024, 7:29:31 AM `
- sha: `1cd65d7`
- branch: `master`

**描述问题**
部署在Cloudflare Workers的telegram chat bot疑似被未授权telegram用户使用。我刚从直接使用OpenAI API换成了用自己部署的[one-api](https://github.com/songquanpeng/one-api)中转，然后设置了一个key给这个telegram bot使用。发现从昨天晚上开始有未授权的telegram用户使用了这个key并且把额度用完了（还好我只设置了2美金）。从对应的KV存储里还能看到聊天记录（查了一下语言是乌孜别克语）. 未授权用户的telegram id是6565401074，1350368887（见截图）。

我也怀疑可能是我的key泄露了，但如果是这样聊天记录应该不会出现在KV存储里？说明是直接使用的telegram bot。而且我在one-api里设置了好几个key，只有这个的使用出了问题。

我确认我的环境变量设置里，`CHAT_WHITE_LIST`没有包含上面提到的两个ID，并且我把`I_AM_A_GENEROUS_PERSON`设置成了false。

**复现问题**
不清楚如何复现。

**预期行为**
部署在Cloudflare Workers的telegram chat bot疑似被未授权telegram用户使用。

**截图**

1. KV存储里记录的未授权用户：
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/e44148de-7cf9-43cc-b1f1-7aeac43ce785">

2. one-api的部分记录：

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/7893ec58-1597-4243-8565-91b0155555a7">

**其他信息**
无。

**Comment by TBXark** [comment]
我用小号测试了一下群组和私聊授权判断都没有问题

@TestChatGPTWorkers_bot

**Comment by TBXark** [comment]
看看你之前是怎么配置的 I_AM_A_GENEROUS_PERSON 
要不然你直接删除 I_AM_A_GENEROUS_PERSON 配置，反正默认是false

**Comment by jinjunliu** [comment]
感谢@TBXark 回复，我删掉了`I_AM_A_GENEROUS_PERSON `配置，并且换了一个key。我也很疑惑为啥会出现这种情况。

**Comment by TBXark** [comment]
我怀疑是不是你的 I_AM_A_GENEROUS_PERSON 设置的有问题，然后被JS判断出true了，毕竟JS这里非空就是true，我可以把这个改成  `ENV.I_AM_A_GENEROUS_PERSON === true`

<img width="381" alt="image" src="https://github.com/user-attachments/assets/dc2b0286-df6f-4856-89e6-56fb3e7d20a0">

**Comment by jinjunliu** [comment]
我设置的是值是`false`，应该不太可能拼错吧😂，现在删了也看不到了

**Comment by jinjunliu** [comment]
有没有可能环境变量里的值会读取成字符串？我不太懂JS，我在浏览器的console里试了一下，如果是字符串的`'false'`，效果和`true`是一样的：

<img width="289" alt="image" src="https://github.com/user-attachments/assets/8c918f64-73c0-4143-9a3a-521fc1531769">

**Comment by TBXark** [comment]
哦 不是这个问题，但是确实有个BUG，马上修改

**Comment by TBXark** [comment]
fix: 配置中bool类型判断错误BUG #290 之前合并配置的时候判断出问题了。应该判断非空，直接拿当前值做条件，导致默认值为false的配置都被当作字符串了

<img width="697" alt="image" src="https://github.com/user-attachments/assets/db3eef6e-240e-4092-ac74-77088aad635b">

**Comment by jinjunliu** [comment]
原来如此，感谢修复！
