### ISSUE TITLE
[BUG]貌似无法支持cf最新推出的flux-1-schnell

### ISSUE THREAD

**Issue by snakeying** [TBXark/ChatGPT-Telegram-Workers#293]
相关文档

https://developers.cloudflare.com/workers-ai/models/flux-1-schnell

我看了一下日志貌似无法读取返回的url，bot返回

ERROR: Bad Request {"ok":false,"error_code":400,"description":"Bad Request: IMAGE_PROCESS_FAILED"}

但不知为何response又返回"status": 200 OK？

**Comment by TBXark** [comment]
dev分支已添加 cloudflare workers ai base64格式图片支持
