### ISSUE TITLE
[BUG] Cohere 对话报错

### ISSUE THREAD

**Issue by djx30103** [TBXark/ChatGPT-Telegram-Workers#299]
![image](https://github.com/user-attachments/assets/cc1bbc84-bec7-4000-bb4d-666963c349f3)

第一次对话正常，后续报错

**Comment by TBXark** [comment]
https://github.com/TBXark/ChatGPT-Telegram-Workers/tree/dev 已在dev中修复，准备合并到master

**Comment by djx30103** [comment]
![image](https://github.com/user-attachments/assets/9d90d6ce-674d-40b5-9b3b-515edd8eb0b0)

现在好像直接就报错了

**Comment by TBXark** [comment]
https://docs.cohere.com/reference/chat 他的API好像是切换成V2了，我改一下吧

**Comment by TBXark** [comment]
已更新v2版本，如果手动设置过 COHERE_API_BASE 需要改为v2
