### ISSUE TITLE
当消息中包含图片或 sticker 时持续报错

### ISSUE THREAD

**Issue by inertia42** [TBXark/ChatGPT-Telegram-Workers#3]
当消息中包含图片或 sticker 时持续报错，报错内容：
```
我不知道该怎么回答
>Cannot read properties of undefined (reading '0')}
```
该报错会持续到用命令 `/new` 重置对话。

**Comment by TBXark** [comment]
已修复 https://github.com/TBXark/ChatGPT-Telegram-Workers/commit/52f6a7b369fe9c09a217f8d3661d44306381446b
