### ISSUE TITLE
/env 会不安全输出

### ISSUE THREAD

**Issue by barry-ai-fork** [TBXark/ChatGPT-Telegram-Workers#30]
if (pathname.startsWith(`/env`)) {
    //return new Response(JSON.stringify(ENV), { status: 200 });
  }

**Comment by TBXark** [comment]
测试的代码 现在删掉

**Comment by barry-ai-fork** [comment]
fyi:

for (let token of ENV.TELEGRAM_AVAILABLE_TOKENS) {
    token = token.replace("\n","")
    const url = `https://${domain}/telegram/${token}/webhook`;
    const id = token.split(':')[0];
    result[id] = {
      webhook: await bindTelegramWebHook(token, url),
      command: await setCommandForTelegram(token),
    };
  }
