### ISSUE TITLE
开了 I_AM_A_GENEROUS_PERSON 但还是不能用

### ISSUE THREAD

**Issue by zzzqu** [TBXark/ChatGPT-Telegram-Workers#31]
提示不是管理员，无法进行操作

**Comment by TBXark** [comment]
你不是这个群的管理员吗

**Comment by zzzqu** [comment]
哦必须要是管理员才可以吗，有没有办法让所有人都可以在群里提问

**Comment by TBXark** [comment]
是所有人都开始 但是部分命令只有管理员可以

**Comment by zzzqu** [comment]
但是我现在的情况是只有bot拥有者可以开始，已经设置过白名单了

**Comment by Cheivin** [comment]
这是个bug

**Comment by zzzqu** [comment]
好的，望修复

**Comment by Cheivin** [comment]
> 好的，望修复

最新构建的测试版本已经修复，https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/84ad30b7b2f392c6434f428535dcd97254083834/dist/index.js

**Comment by zzzqu** [comment]
最新版本可以了，但是/new /start等命令群组成员无法使用，这个权限我觉得可以给，还有就是群组成员必须要回复bot信息才可以使用，直接@bot无法使用！

**Comment by Cheivin** [comment]
到`@BotFather`那确认一下机器人的`privacy`状态是`DISABLED`
<img width="580" alt="image" src="https://user-images.githubusercontent.com/19513276/223393679-75090dc3-36e8-47f5-b470-ba1e6cd01f32.png">
