### ISSUE TITLE
[Feature Request] 添加多模态模型的识图(Vision)支持

### ISSUE THREAD

**Issue by Kosette** [TBXark/ChatGPT-Telegram-Workers#313]
不知道能否添加多模态模型的识图的支持，现在似乎只能输入text prompt。

**Comment by TBXark** [comment]
openai和Claude是支持的，具体可能得看你的模型和AI提供商

**Comment by TBXark** [comment]
那你得模型支持图片才行，而且你的兼容的api需要的图片格式和openai的一致，都是使用URL

**Comment by TBXark** [comment]
支持图文消息，不过图片是以URL的格式发送的
