### ISSUE TITLE
变量值怎么写

### ISSUE THREAD

**Issue by victorzone** [TBXark/ChatGPT-Telegram-Workers#33]
GROUP_CHAT_BOT_ENABLE

这个变量怎么填啊？ true还是enable？  请详细加进说明啊 感谢

**Comment by Cheivin** [comment]
如果要开启群组聊天，`GROUP_CHAT_BOT_ENABLE `填`true`。目前群组聊天功能有bug，仅管理员可以与机器人互动，测试分支已尝试修复，未合并至master

**Comment by TBXark** [comment]
`true` 这个默认是`true`

**Comment by qhgy** [comment]
管理员也没法互动啊
