### ISSUE TITLE
CHAT_GROUP_WHITE_LIST用法

### ISSUE THREAD

**Issue by victorzone** [TBXark/ChatGPT-Telegram-Workers#34]
这个是填写url里那个自设的user ID是吗？还是一串数字？

**Comment by Cheivin** [comment]
将机器人添加到群组，发送`/new`或者`/start`，机器人会回复群ID，`CHAT_GROUP_WHITE_LIST `填的就是这个ID。
如果是单个群，假设机器人回复的群A的ID是`-100000000`：
`CHAT_GROUP_WHITE_LIST `填`-100000000`
如果是多个群，
假设群A的ID是`-100000000`，群B的ID是`-100000001`，`CHAT_GROUP_WHITE_LIST `填`-100000000,-100000001`
![image](https://user-images.githubusercontent.com/19513276/223348679-8dd5e726-fcb2-4b1a-927e-a84f43ed9ce6.png)

**Comment by qhgy** [comment]
感恩的心，感谢有你
