### ISSUE TITLE
群内怎样配置  /setenv SYSTEM_INIT_MESSAGE

### ISSUE THREAD

**Issue by victorzone** [TBXark/ChatGPT-Telegram-Workers#36]
/setenv SYSTEM_INIT_MESSAGE="现在开始是喵娘，每句话已喵结尾。"
群里我用了这个 出现下边的，该怎么办？

说了更新成功。 但是仍然没有变化？是不是群设置有什么特别？

**Comment by TBXark** [comment]
试一下引用机器人的消息然后加上这段命令

**Comment by yourswoo** [comment]
我的也是这样，提示更新配置成功。实际还是默认的。私聊和群聊都是这样

**Comment by Cheivin** [comment]
设置过后，试试`/new`开始新的对话
