### ISSUE TITLE
命令/new ， 机器人回复：我不知道该怎么回答 > Unexpected token '<', "<!DOCTYPE "... is not valid JSON}

### ISSUE THREAD

**Issue by zangrong** [TBXark/ChatGPT-Telegram-Workers#41]
先是 internal server error，我把api.openai.com换成了一个代理后的地址（这个地址我在其他程序里调用可以正常用）。
然后敲入命令 /new ，机器人回复：我不知道该怎么回答 > Unexpected token '<', "<!DOCTYPE "... is not valid JSON}

**Comment by Guojingxing** [comment]
我也遇到了这个问题
![image](https://user-images.githubusercontent.com/33157458/223422881-94cb9f9d-37c5-45d5-af93-3c7555b4c8b2.png)

**Comment by TBXark** [comment]
![image](https://user-images.githubusercontent.com/9513891/223427537-7161bdab-f9e9-4ff2-aea3-423c428d01fe.png)

应该是openai的问题吧 稍后再试一下
