### ISSUE TITLE
请教一下，为什么KV里会保存完整的聊天记录？

### ISSUE THREAD

**Issue by CCCAUCHY** [TBXark/ChatGPT-Telegram-Workers#43]
根据openai的官方POST示例，有chatid，应该没必要保存吧。
而且如果bot没有重新发送历史消息的功能，那么我认为甚至都不需要保存任何聊天记录，只需要保存chatid和userid的关系就行了。
难道chatGPT记忆上下文的智能是通过一次性提交全部聊天记录实现的？

**Comment by TBXark** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/9513891/223452217-afc06376-0819-4aeb-8ed0-5a839754e165.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/9513891/223452330-d3c53720-0f0f-455c-8a1f-a662c4f6837f.png">
你说的Example是这个么，之前那些通过抓包解析的API可能有这个功能，但是官方公布的API没有这个功能

**Comment by AnotiaWang** [comment]
ChatGPT 官方版应该是有个 `conversationId`，多轮对话只需要传入这个值就可以，因为 OpenAI 会帮你存聊天历史，也方便自己做分析。商业化接口是可以不允许 OpenAI 分析数据的，也就是说这些上下文得自己存。
