### ISSUE TITLE
自动更新疑似会删除Worker的环境变量和KV绑定

### ISSUE THREAD

**Issue by imldy** [TBXark/ChatGPT-Telegram-Workers#52]
**Cloudflare API Token使用的`Edit Cloudflare Workers`模板创建的，权限如下：**

![image](https://user-images.githubusercontent.com/53949747/223624791-4bf0bb5d-46ca-4048-90da-e989a065a425.png)

**在自己仓库-Actions-Deploy to Cloudflare Workers-Run workflow后**

![image](https://user-images.githubusercontent.com/53949747/223624961-cedb3488-2aef-4623-863e-2dab7ec259bc.png)

**Worker的环境变量和KV绑定消失了**

![image](https://user-images.githubusercontent.com/53949747/223625014-dd6a978c-01b9-4edf-8ec4-0382b409cbc3.png)

**Comment by imldy** [comment]
第二次尝试也会复现

**Comment by imldy** [comment]
#51

**Comment by TBXark** [comment]
- 已修复现在需要填写完整 `wrangler.toml` 保证数据不丢失
