### ISSUE TITLE
是否考虑更换 GPT-3.5 model?

### ISSUE THREAD

**Issue by allenforrest** [TBXark/ChatGPT-Telegram-Workers#55]
代码中目前定义的是 gpt-3.5-turbo，是否考虑更新为 gpt-3.5-turbo-0301，甚至开放用户通过 Variable 自定义？

**Comment by TBXark** [comment]
- 倒是可以加不过，目前的话dist代码没有压缩混淆 手动改一下还是很方便的

**Comment by allenforrest** [comment]
嗯嗯，我现在是手工改了哈

**Comment by Cheivin** [comment]
> 嗯嗯，我现在是手工改了哈

https://github.com/TBXark/ChatGPT-Telegram-Workers/tree/96ee23d3e01a122df0aa6d1f52d4addbb21229e9
