### ISSUE TITLE
进入新建的workers, 选择Quick Edit, 将./dist/index.js代码复制到编辑器中

### ISSUE THREAD

**Issue by simplesafe** [TBXark/ChatGPT-Telegram-Workers#60]
这一步能放一个screenshot吗？不知道在什么地方加这段代码。

**Comment by Cheivin** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/19513276/223643304-323e748f-def3-496d-a25b-63049d6a3c98.png">
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/19513276/223643602-c34cf713-d3f4-4fa8-b7f5-97a370f8e1d3.png">
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/19513276/223643916-a7932ec0-0482-4472-8802-0060a02ed04b.png">

**Comment by simplesafe** [comment]
完美解决！谢谢!
