### ISSUE TITLE
有可能开发微信版本的吗

### ISSUE THREAD

**Issue by daheitian** [TBXark/ChatGPT-Telegram-Workers#61]
我自己按照教程部署好了，非常棒。在即刻上推广下

**Comment by imldy** [comment]
做微信ChatGPT有很多工具了吧，目前这个程序最亮的功能支持多机器人多配置的功能，放在微信上面就很难使用，因为微信号也太难注册、登录了

**Comment by daheitian** [comment]
确实，你这个是我第一次按照教程搞定的程序，之前我有尝试过其他部署到微信的对我来说太复杂了，很棒。微信确实封闭

**Comment by TBXark** [comment]
其实国内服务器不加代理访问workers.dev的域名都费劲
