### ISSUE TITLE
将./dist/index.js代码复制到编辑器中,保存，文件不存在

### ISSUE THREAD

**Issue by xieyqxie** [TBXark/ChatGPT-Telegram-Workers#64]
显示不存在

**Comment by ddzzhen** [comment]
直接在库里找，在dist文件夹里，这个库目前更新很快，可能是网站上的链接有变动

**Comment by TBXark** [comment]
路径错了 现在修改一下

**Comment by TBXark** [comment]
https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js
