### ISSUE TITLE
访问 init 时会报 "ok":false "error_code":404 错误，附临时解决办法

### ISSUE THREAD

**Issue by XueshiQiao** [TBXark/ChatGPT-Telegram-Workers#65]
设置参数时，使用 TELEGRAM_AVAILABLE_TOKENS  会有如下 errorcode 404 错误， 改为使用 TELEGRAM_TOKEN 可以正常work。

```
Webhook: {"ok":false,"error_code":404,"description":"Not Found"}

Command: {"ok":false,"error_code":404,"description":"Not Found"}
```

**Comment by TBXark** [comment]
- 这就有点神奇

**Comment by lichenbuliren** [comment]
我访问 workers  无响应怎么回事，不知道哪里配置错了

**Comment by damozhang** [comment]
在我的案例中，添加变量 TELEGRAM_BOT_NAME 后问题解决。
https://github.com/TBXark/ChatGPT-Telegram-Workers/issues/25#issuecomment-1460496679
