### ISSUE TITLE
4096限制

### ISSUE THREAD

**Issue by Royage888** [TBXark/ChatGPT-Telegram-Workers#7]
在聊天中仍存在4096限制,发现一个项目,看能不能突破下
[https://twitter.com/mckaywrigley/status/1631328308116996097](url)

**Comment by TBXark** [comment]
这个确实是有，我看看怎么能控制在单文件部署基础上进行优化。

**Comment by sandlong** [comment]
我遇到的一个项目的做法是，设定了一个参数来决定 每次发送最新N条而非全部对话记录，比如每次发最新的10条。这样的话理论上对话可以一直继续下去，只要N选的合适，就不会碰到4096的限制，也不太可能丢失对话语境，同时也不会有token花费越来越多的问题。可以参考一下。

**Comment by TBXark** [comment]
> 我遇到的一个项目的做法是，设定了一个参数来决定 每次发送最新N条而非全部对话记录，比如每次发最新的10条。这样的话理论上对话可以一直继续下去，只要N选的合适，就不会碰到4096的限制，也不太可能丢失对话语境，同时也不会有token花费越来越多的问题。可以参考一下。

确实可以，给历史记录加个过期时间和最大长度 的配置选项
