### ISSUE TITLE
设置AUTO_TRIM_HISTORY为true时，SYSTEM_INIT_MESSAGE不起作用，消息被裁剪后系统提示变成了默认的

### ISSUE THREAD

**Issue by imldy** [TBXark/ChatGPT-Telegram-Workers#71]
开/关AUTO_TRIM_HISTORY两次测试生成的历史记录不同

BUG发生在自动裁剪、new对话后

![image](https://user-images.githubusercontent.com/53949747/223707208-648c666f-620e-40c1-b534-aa9cb9d3dd90.png)

![image](https://user-images.githubusercontent.com/53949747/223707929-d91d3c39-eadd-4605-95f7-e03b04090da6.png)

**Comment by imldy** [comment]
#69

**Comment by imldy** [comment]
> /version 的版本号是什么

当前已经是最新版本, 当前版本: {"ts":1678245405,"sha":"451537f"}

**Comment by TBXark** [comment]
> > /version 的版本号是什么
> 
> 
> 
> 当前已经是最新版本, 当前版本: {"ts":1678245405,"sha":"451537f"}

dev里的编译版应该是已经修复了
