### ISSUE TITLE
建议在用户配置里增加自定义的MAX_HISTORY_LENGTH和AUTO_TRIM_HISTORY

### ISSUE THREAD

**Issue by CCCAUCHY** [TBXark/ChatGPT-Telegram-Workers#76]
需求是一问一答的机器人，每次发送new有点麻烦。
这样也能节省token，一个worker多个用户，每个用户有自己的MAX_HISTORY_LENGTH和AUTO_TRIM_HISTORY。
或者至少自动new，因为目前我只能想到要么一问一答，要么聊起来就不知道历史记录能聊有多长了。

**Comment by TBXark** [comment]
已经有了这个配置 你可以把MAX_HISTORY_LENGTH设置成0

**Comment by TBXark** [comment]
感觉就算每个用户有自己的配置 还得根据系统的来不能超过 不然用户设置一个超大的就超过了系统的限制了

**Comment by CCCAUCHY** [comment]
> 感觉就算每个用户有自己的配置 还得根据系统的来不能超过 不然用户设置一个超大的就超过了系统的限制了

是的，全局和每个用户都有这个变量

**Comment by zzzqu** [comment]
> 

![Screenshot_2023-03-10-11-17-27-859_org telegram plus](https://user-images.githubusercontent.com/77374843/224214626-fc9f944e-1ce6-44ba-8bff-2f36d8d5bd00.png)


设置为0没用，还是记录上下文

**Comment by TBXark** [comment]
看了一下代码 发现不能处理等于0的情况 dev稍后优化
________________________________
