### ISSUE TITLE
 Workers KV中，存储用户配置的key为`NaN`，历史记录key为`history:用户id`，那多个bot不会混乱吗？

### ISSUE THREAD

**Issue by imldy** [TBXark/ChatGPT-Telegram-Workers#8]

**Comment by imldy** [comment]
@inertia42 感谢， 你的方法的是对的。可以解决存储用户配置的问题。

**Comment by imldy** [comment]
历史记录也应该是包含机器人ID的，期待作者修复。

**Comment by TBXark** [comment]
确实 稍后我修复一下这个bug

**Comment by TBXark** [comment]
@imldy 已修复

**Comment by woaini2022520** [comment]
为什么我把代码复制到编辑器显示的是：NOTFOUND: /

**Comment by TBXark** [comment]
> 为什么我把代码复制到编辑器显示的是：NOTFOUND: /

截个图看看？

**Comment by TBXark** [comment]
> 为什么我把代码复制到编辑器显示的是：NOTFOUND: /

我知道了 是旁边的预览界面 因为没有处理主页的路由 所以是notfound 这个接口没啥用 没有影响

**Comment by woaini2022520** [comment]
[{"ok":true,"result":true,"description":"Webhook was set"}]    显示这个是否证明已经成功了，但是我在机器人里面发信息没回应

**Comment by TBXark** [comment]
> @TBXark 你好，msgCreateNewChatContext 中关于 history 的 key 还有点问题
> 
> https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/25cf066a42e87db36da908e0970269849340a735/index.js#L262

THANKS 现在修复
