### ISSUE TITLE
请问如何像web端一样管理不同topic？

### ISSUE THREAD

**Issue by victorxys** [TBXark/ChatGPT-Telegram-Workers#80]
请问如何像web端一样管理不同topic？
便于对不同的topic设置不同功能的助理从而进行调教

**Comment by TBXark** [comment]
- 可以建立多个群，每个群只有自己个机器人，每个群的机器人赋予不一样的`SYSTEM_INIT_MESSAGE`

**Comment by victorxys** [comment]
好的，明白了，这个确实是个解决方案，谢谢

**Comment by victorxys** [comment]
但是 “SYSTEM_INIT_MESSAGE”不是群组属性吧？是基本配置？

**Comment by victorxys** [comment]
> * 可以建立多个群，每个群只有自己个机器人，每个群的机器人赋予不一样的`SYSTEM_INIT_MESSAGE`
但是我看到 “SYSTEM_INIT_MESSAGE”不是群组属性吧？是基本配置？
一个worker中的  SYSTEM_INIT_MESSAGE 可以是多个值吗？
--


<br class="Apple-interchange-newline">

**Comment by Cheivin** [comment]
`SYSTEM_INIT_MESSAGE`是公共默认的，如果你在群里设置了`SYSTEM_INIT_MESSAGE`，那么这个群以你设置的为主

**Comment by victorxys** [comment]
> `SYSTEM_INIT_MESSAGE`是公共默认的，如果你在群里通过`/setenv`设置了`SYSTEM_INIT_MESSAGE`，那么这个群以你设置的为主

哦，好的，这是群组的解决方式，我看作者提到的那个最佳实践，通过多个bot来解决，每个bot的  SYSTEM_INIT_MESSAGE 不同，这种方式怎么设置呢？  SYSTEM_INIT_MESSAGE 支持逗号分隔然后对应 bot_avilable_token 吗？

**Comment by Cheivin** [comment]
> > `SYSTEM_INIT_MESSAGE`是公共默认的，如果你在群里通过`/setenv`设置了`SYSTEM_INIT_MESSAGE`，那么这个群以你设置的为主
> 
> 哦，好的，这是群组的解决方式，我看作者提到的那个最佳实践，通过多个bot来解决，每个bot的 SYSTEM_INIT_MESSAGE 不同，这种方式怎么设置呢？ SYSTEM_INIT_MESSAGE 支持逗号分隔然后对应 bot_avilable_token 吗？

1. 环境变量中设置的`SYSTEM_INIT_MESSAGE`对于所有机器人都是公共的
2. 当`GROUP_CHAT_BOT_SHARE_MODE`配置为`false`(默认`false`)时：
   1. 仅管理员可以在群里通过`/setenv`设置`SYSTEM_INIT_MESSAGE`，对整个群生效。
   2. 不同群的同一个机器人，仅对当前群生效。
   3. 同一个群不同的机器人，仅对设置时`@`的那个机器人生效。
4. 当`GROUP_CHAT_BOT_SHARE_MODE`配置为`true`(默认`false`)时：
   1. 群员可以在群里设置自己的`SYSTEM_INIT_MESSAGE`，每个群员的配置相互独立。
   2. 不同群的同一个机器人，仅对当前群生效。
   3. 同一个群不同的机器人，仅对设置时`@`的那个机器人生效。

**Comment by victorxys** [comment]
> > > `SYSTEM_INIT_MESSAGE`是公共默认的，如果你在群里通过`/setenv`设置了`SYSTEM_INIT_MESSAGE`，那么这个群以你设置的为主
> > 
> > 
> > 哦，好的，这是群组的解决方式，我看作者提到的那个最佳实践，通过多个bot来解决，每个bot的 SYSTEM_INIT_MESSAGE 不同，这种方式怎么设置呢？ SYSTEM_INIT_MESSAGE 支持逗号分隔然后对应 bot_avilable_token 吗？
> 
> 1. 环境变量中设置的`SYSTEM_INIT_MESSAGE`对于所有机器人都是公共的
> 2. 当`GROUP_CHAT_BOT_SHARE_MODE`配置为`true`(默认`false`)时：
>    
>    1. 仅管理员可以在群里通过`/setenv`设置`SYSTEM_INIT_MESSAGE`，对整个群生效。
>    2. 不同群的同一个机器人，仅对当前群生效。
>    3. 同一个群不同的机器人，仅对设置时`@`的那个机器人生效。
> 3. 当`GROUP_CHAT_BOT_SHARE_MODE`配置为`false`(默认`false`)时：
>    
>    1. 群员可以在群里设置自己的`SYSTEM_INIT_MESSAGE`，每个群员的配置相互独立。
>    2. 不同群的同一个机器人，仅对当前群生效。
>    3. 同一个群不同的机器人，仅对设置时`@`的那个机器人生效。

好的，明白了，您解释的非常详细，十分感谢！
