### ISSUE TITLE
建议更换不当范例

### ISSUE THREAD

**Issue by gasolin** [TBXark/ChatGPT-Telegram-Workers#81]
我发现在您的项目中，有一个范例可能不太恰当。具体来说，我在您的 README 发现了一个包含争议性观点的示例，我认为这样的例子不应该出现在您的项目中。

作为一个开源社区的成员，我们应该共同创建一个友善、包容的开发环境。我相信这个范例对您只是图一乐，但是它仍然会给其他人带来不适，并且对社区造成负面影响。

我建议您尽快更换这个范例，避免对其他人造成不必要的伤害。如果您需要任何帮助或建议，请随时让我知道，我很乐意提供帮助。

**Comment by uirozwang** [comment]
沒事的，這裡是有言論自由的地方，任何人都可以表達自己的觀點，而我作為一名身處自由社會的台灣人，很樂意尊重他在公眾場合自慰的需求。

**Comment by gasolin** [comment]
@TBXark 对于 `wontfix` 这反应感到相当失望，看到示例的台湾人，后续可能都不会再和这专案有友好的交流
