### ISSUE TITLE
聊天机器人显示openapikey未设置咋办[BUG]

### ISSUE THREAD

**Issue by grelim07713** [TBXark/ChatGPT-Telegram-Workers#89]
[**版本号**](url)
> 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
- ts: `BUILD_TIMESTAMP `
- sha: `BUILD_VERSION`

**描述问题**
简要而清晰地解释问题。

**复现问题**
重现问题的步骤：
1. 进入“...”
2. 点击“...”
3. 发送到“...”

**预期行为**
简要而清晰地说明预期的行为。

**截图**
如适用，包括截图以帮助说明问题。

**其他信息**
提供与问题相关的任何其他信息。

**Comment by Cheivin** [comment]
> [**版本号**](url)
> 
> > 你可以在代码编辑器中前几行找到, 它们分别是`BUILD_TIMESTAMP`和`BUILD_VERSION`, 这俩个数据对于我们定位问题非常重要]
> 
> * ts: `BUILD_TIMESTAMP `
> * sha: `BUILD_VERSION`
> 
> **描述问题** 简要而清晰地解释问题。
> 
> **复现问题** 重现问题的步骤：
> 
> 1. 进入“...”
> 2. 点击“...”
> 3. 发送到“...”
> 
> **预期行为** 简要而清晰地说明预期的行为。
> 
> **截图** 如适用，包括截图以帮助说明问题。
> 
> **其他信息** 提供与问题相关的任何其他信息。

截图中的key涉及到你账号安全，我帮你把截图删了。

另外可以试试最新的dev版本，以及把`TELEGRAM_BOT_NAME`填上

**Comment by grelim07713** [comment]
> 
谢谢您，请问怎样试用最新的dev版本呢？

**Comment by TBXark** [comment]
> 谢谢您，请问怎样试用最新的dev版本呢？

https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/dev/dist/index.js

**Comment by grelim07713** [comment]
> > 谢谢您，请问怎样试用最新的dev版本呢？
> 
> https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/dev/dist/index.js

![Screenshot_20230309_231542](https://user-images.githubusercontent.com/127404894/224068590-63b481e4-7a1a-428f-a04a-44f92d284698.jpg)
出现了这个，请问怎样才能解决呢

**Comment by TBXark** [comment]
那就是你没有设置API_KEY, 去这里填写

<img width="593" alt="image" src="https://user-images.githubusercontent.com/9513891/224069194-199cf694-990a-4a82-9325-5e32158af664.png">

**Comment by grelim07713** [comment]
> 那就是你没有设置API_KEY, 去这里填写
> 
> <img alt="image" width="593" src="https://user-images.githubusercontent.com/9513891/224069194-199cf694-990a-4a82-9325-5e32158af664.png">

![image](https://user-images.githubusercontent.com/127404894/224070844-95e61439-c570-42f6-9bbb-bda89087e8de.png)
可是我写了的呀

**Comment by grelim07713** [comment]
您好，还在吗?

**Comment by TBXark** [comment]
要不你删了这个变量重新输入一次
________________________________

**Comment by grelim07713** [comment]
解决了，但是他不回我

**Comment by TBXark** [comment]
首页点击 click here 了没

**Comment by TBXark** [comment]
你这个免费账号失效了 得绑信用卡了
________________________________

**Comment by grelim07713** [comment]
好吧，谢谢大佬，麻烦了
