### ISSUE TITLE
一个KV每天只能写1000次是不是不太够用

### ISSUE THREAD

**Issue by sandlong** [TBXark/ChatGPT-Telegram-Workers#91]
如果我没搞错的话，好像一来一回就要消耗2个写操作，这样一个机器人一天岂不是只能对话500个回合？

**Comment by TBXark** [comment]
可以处理一下kv写入失败不报错和关闭使用统计。这样可以存1000次对话，超过后只是没有历史记录还能正常对话。

**Comment by sandlong** [comment]
那样就没有上下文了吧。不过也还好。如果有一天不够我用的，我就去买cf worker的paid plan。😉

**Comment by TBXark** [comment]
注册多几个账号就行😂
________________________________

**Comment by TBXark** [comment]
`dev` 添加了`ENABLE_USAGE_STATISTICS` 环境变量，可以关掉统计节省一半写入

**Comment by katcu** [comment]
每天只能写1000次是什么意思？ chatgpt的API keys有限制吗？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
