### ISSUE TITLE
用telegram editMessageText API实现流式输出

### ISSUE THREAD

**Issue by Qchsi** [TBXark/ChatGPT-Telegram-Workers#93]
https://twitter.com/wsvn53/status/1633799055167066113  能否实现这个功能呢？

**Comment by TBXark** [comment]
挺6，就不知道这么用workers会不会超过单个执行的时间限制。

**Comment by mithew** [comment]
这样眼睛有点累噢，不如原来

**Comment by mithew** [comment]
这个在网页上还好，因为网页位置不会移动，文字逐渐往下延长，不影响眼睛疲劳，而且看起来科技感十足。

但是在tg里，每显示一小段新信息，屏幕就会跳动一次，很痛苦的（其他项目试过了）

**Comment by TBXark** [comment]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/9513891/232455775-c2f36db5-9de4-4ea0-abe2-2175a2e89e80.png">
简单尝试后发现容易超时，预计暂时不实现该功能。

**Comment by wsvn53** [comment]
可以实现，我就是这条推文作者，我是基于 CF Workers 实现的效果 😂

**Comment by TBXark** [comment]
> 可以实现，我就是这条推文作者，我是基于 CF Workers 实现的效果 😂

6. 你这边具体怎么实现的，我写了一下会超时呢。

**Comment by wsvn53** [comment]
> 

稍晚些我整理些关键代码供你参考

**Comment by TBXark** [comment]
> 稍晚些我整理些关键代码供你参考

我好像找到办法了，看到有人成功又去钻研了一下，😂

**Comment by TBXark** [comment]
> 稍晚些我整理些关键代码供你参考

<img width="469" alt="image" src="https://user-images.githubusercontent.com/9513891/233338743-965834f9-10df-4e5f-9122-4cf250318d98.png">
但是长一点还是会超时，所以感觉还是用不上

**Comment by TBXark** [comment]
这个是我的测试代码

```js

const config = {
  apiKey: "sk-"
}
async function test() {
  const response = await fetch('https://closeai.tbxark.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${config.apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      "stream": true,
      "model": "gpt-3.5-turbo",
      "messages": [{"role": "user", "content": "Go怎么反转二叉树"}]
    }),
  });
  const reader = response.body?.pipeThrough(new TextDecoderStream()).getReader();
  if (!reader) return;
  var textDecoder = new TextDecoder();
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    console.log(textDecoder.decode(value))
  }
}

export default {
  async fetch(request, env) {
    await test()
    return new Response("Hello world")
  }
}

```

**Comment by wsvn53** [comment]
以下是我这边的核心实现，原本是想做好了开源出来，实在没时间，辛苦 repo 主实现方便大家也是挺好的：

核心逻辑是通过 byob reader 缓冲降低 decode 和回调的频率，减少 cpu time limit 的次数，这个方法基本可以应付 90% 的场景，特殊场景下可以通过 retry mode 的设计来补救，因为 telegram 在调用失败后会尝试重新请求，因此可以在 KV 对同一个请求做个标记

```
async function invokeOpenAIAPI(params, onStreamData) {
    // request openai api
    const url = 'https://api.openai.com/v1/chat/completions';
    let retryMode = params.retry;
    delete params.retry;

    console.log('OpenAI params:', JSON.stringify(params));
    let response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + envs.OPENAI_TOKEN,
        },
        body: JSON.stringify(Object.assign({}, OPENAI_PARAMS, params)),
    });

    var contentFull = '';

    // 注：这里增加 retryMode 是为了防止实在是很长很长的内容导致 CPU time limit 了的补救措施，改编成非 streaming 接口直接返回，这里可以自行做些逻辑处理
    if (retryMode) {
        contentFull = await response.text();
        console.log('In retry mode:', contentFull);
        let content = extractContentFromStreamData(contentFull);
        return content.content;
    }

    let reader = response.body.getReader({ mode: 'byob' });
    var data = { done: false };
    const decoder = new TextDecoder('utf-8');
    var pendingText = '';
    while (data.done == false) {
        // 注：通过 buffer 读取，可以避免轮训太多次已经导致太频繁的 decode 和 太频繁的回调导致消耗 cpu 时间片
        // 经过多轮测试后，这个 buffer size 数量是比较不容易超时的，基本能应付 90% 场景，实在是部分过于大的输出可通过上述的 retry mode 补救
        data = await reader.readAtLeast(4096, new Uint8Array(5000));
        const text = decoder.decode(data.value);
        pendingText = pendingText + text;
        let content = extractContentFromStreamData(pendingText);
        pendingText = content.pending;
        contentFull = contentFull + content.content;
        if (data.done == false) {
            await onStreamData(contentFull);
        }
    }

    return contentFull;
}
```

**Comment by TBXark** [comment]
> contentFull;

thanks，超时这个确实是没有什么好的办法解决。存kv最大的缺点就是太消耗写入次数了。低频使用还行。回头看看tg重试的时候有没有什么标志位发生变化。

**Comment by TBXark** [comment]
dev 已添加此功能可以设置  `STREAM_MODE`  为 `true` 体验。 防止超时的安全模式之后添加。

**Comment by wsvn53** [comment]
> @wsvn53 你这个 `extractContentFromStreamData` 具体怎么实现，我用正则实现不知道会不会太耗时呢。
> 
> ```js
> function extractContentFromStreamData(stream) {
> 	let matches = stream.match(/data:\s*({[\s\S]*?})(?=\s*data:|$)/g);
> 	let remainingStr = stream;
> 	let contentStr = ""
> 	matches?.forEach(match => {
> 		try {
> 			let matchStartIndex = remainingStr.indexOf(match);
> 			let jsonStr = match.substr(6);
>       console.log(jsonStr)
> 			let jsonObj = JSON.parse(jsonStr);
>       contentStr += jsonObj.choices[0].delta?.content || ''
> 			remainingStr = remainingStr.slice(matchStartIndex + match.length);
> 		} catch (e) {
> 			console.error(e)
> 		}
> 	});
> 	return {
> 		content: contentStr,
> 		pending: remainingStr
> 	}
> }
> ```

我是直接分割成行，取行首的 data: 后的数据，这样运算量小一点，取完后去 try JSON.parse 错误了就忽略，留着继续接收数据

**Comment by TBXark** [comment]
@wsvn53 👌，确实，如果一个json就是一行那就没有问题。
