### ISSUE TITLE
账号废了，可能是这个调用方式的问题吗？

### ISSUE THREAD

**Issue by gaopu** [TBXark/ChatGPT-Telegram-Workers#95]
调用接口显示：
OpenAI API 错误
> Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.}

发给我的邮件：
Hi there,
After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.
Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our content policy, repeated attempts at disallowed use-cases, or accessing the API from an unsupported location. You may also wish to review our Terms of Use.
If you believe this is in error and would like to appeal, please contact us through our help center. We will review appeals within one business day and will contact you if we reinstate access to the API.
Best,
The OpenAI team
If you have any questions please contact us through our help center

**Comment by TBXark** [comment]
你这是和别人共享了key吗
