### ISSUE TITLE
请问这个按钮怎么隐藏，我基本用不到，，存在感太强了

### ISSUE THREAD

**Issue by mithew** [TBXark/ChatGPT-Telegram-Workers#98]
![Screenshot_20230310-211402_Telegram](https://user-images.githubusercontent.com/43675269/224457528-4a1ee222-b07a-4c4f-9808-3384db5bc673.png)

**Comment by Arturia169** [comment]
为什么我没有

**Comment by Guojingxing** [comment]
我也没有

**Comment by DoingDog** [comment]
![image](https://user-images.githubusercontent.com/72430078/224470367-4bc46fc8-28ae-4eb7-b94d-e19ad3c1d424.png)
我的有

**Comment by yiiyahui** [comment]
同问，谁提的意见，相当之蛋疼，在一聊天界面上挂着一串大灯笼的感觉。
无比的难受有没有

**Comment by mithew** [comment]
> 同问，谁提的意见，相当之蛋疼，在一聊天界面上挂着一串大灯笼的感觉。 无比的难受有没有

是啊，现在都不太想截图分享了，太丑了

**Comment by yiiyahui** [comment]
按一下/new有那么难嘛 ，这个真心是太抽象了
可以先[退回这里](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/00efc88abe88a117c806e63c9674e5b2f930412f/dist/index.js)
强烈呼吁作者，去掉这两个大灯笼或者至少加个变量😢😢😢😢😢😢😢😢

**Comment by TBXark** [comment]
dev版本已删除

**Comment by TBXark** [comment]
> 按一下/new有那么难嘛 ，这个真心是太抽象了
> 
> 可以先[退回这里](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/00efc88abe88a117c806e63c9674e5b2f930412f/dist/index.js)
> 
> 强烈呼吁作者，去掉这两个大灯笼或者至少加个变量😢😢😢😢😢😢😢😢

本来是在配置里的 dev里面打开了 但是没有合并到主分支

**Comment by mithew** [comment]
辛苦大哥了，已更新 dev 正常了
